/****** Object:  UserDefinedTableType [dbo].[VehicleSchemaV2]    Script Date: 11/20/2019 11:25:27 AM ******/
CREATE TYPE [dbo].[VehicleSchemaV2] AS TABLE(
	[Id] [bigint] NOT NULL,
	[VehicleCode] [nvarchar](100) NULL,
	[Make] [nvarchar](100) NULL,
	[Model] [nvarchar](100) NULL,
	[VehicleType] [nvarchar](100) NULL,
	[BodyType] [nvarchar](100) NULL,
	[IntroductionDate] [date] NULL,
	[ModelYear] [int] NULL,
	[TerminationDate] [date] NULL,
	[EngineCapacity] [int] NULL,
	[EnginePower] [nvarchar](100) NULL,
	[Cylinders] [int] NULL,
	[Doors] [nvarchar](100) NULL,
	[CountryId] [bigint] NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [date] NOT NULL,
	[ModifiedDate] [date] NULL,
	[CreatedBy] [int] NOT NULL,
	[ModifiedBy] [int] NULL,
	[RegYear] [int] NULL,
	[Variant] [nvarchar](200) NULL,
	[PublicationSection] [nvarchar](100) NULL,
	[MasterModel] [nvarchar](100) NULL,
	[MakeCode] [nvarchar](100) NULL,
	[ModelCode] [nvarchar](100) NULL,
	[VariantCode] [nvarchar](100) NULL,
	[AxleConfiguration] [nvarchar](100) NULL,
	[Drive] [nvarchar](100) NULL,
	[Seats] [int] NULL,
	[Use] [nvarchar](100) NULL,
	[WheelBase] [nvarchar](100) NULL,
	[TransmissionType] [nvarchar](50) NULL,
	[NoGears] [int] NULL,
	[Cooling] [nvarchar](100) NULL,
	[CylConfiguration] [nvarchar](50) NULL,
	[EngineCycle] [int] NULL,
	[FuelTankSize] [decimal](18, 2) NULL,
	[FuelType] [nvarchar](50) NULL,
	[TurboOrSuperCharged] [nvarchar](50) NULL,
	[GCM] [int] NULL,
	[GVM] [int] NULL,
	[Tare] [int] NULL,
	[Origin] [nvarchar](50) NULL,
	[FrontNoTyres] [int] NULL,
	[FrontTyreSize] [nvarchar](50) NULL,
	[RearNoTyres] [int] NULL,
	[RearTyreSize] [nvarchar](50) NULL,
	[CO2] [int] NULL,
	[Length] [int] NULL,
	[Height] [int] NULL,
	[Width] [int] NULL,
	[NewListPrice] [decimal](18, 2) NULL,
	[SequenceNumber] [bigint] NOT NULL
)