CREATE TYPE [dbo].[VehicleSchemaV2] AS TABLE (
    [Id]                  BIGINT          NOT NULL,
    [VehicleCode]         NVARCHAR (100)  NULL,
    [Make]                NVARCHAR (100)  NULL,
    [Model]               NVARCHAR (100)  NULL,
    [VehicleType]         NVARCHAR (100)  NULL,
    [BodyType]            NVARCHAR (100)  NULL,
    [IntroductionDate]    DATE            NULL,
    [ModelYear]           INT             NULL,
    [TerminationDate]     DATE            NULL,
    [EngineCapacity]      INT             NULL,
    [EnginePower]         NVARCHAR (100)  NULL,
    [Cylinders]           INT             NULL,
    [Doors]               NVARCHAR (100)  NULL,
    [CountryId]           BIGINT          NULL,
    [IsActive]            BIT             NOT NULL,
    [CreatedDate]         DATE            NOT NULL,
    [ModifiedDate]        DATE            NULL,
    [CreatedBy]           INT             NOT NULL,
    [ModifiedBy]          INT             NULL,
    [RegYear]             INT             NULL,
    [Variant]             NVARCHAR (200)  NULL,
    [PublicationSection]  NVARCHAR (100)  NULL,
    [MasterModel]         NVARCHAR (100)  NULL,
    [MakeCode]            NVARCHAR (100)  NULL,
    [ModelCode]           NVARCHAR (100)  NULL,
    [VariantCode]         NVARCHAR (100)  NULL,
    [AxleConfiguration]   NVARCHAR (100)  NULL,
    [Drive]               NVARCHAR (100)  NULL,
    [Seats]               INT             NULL,
    [Use]                 NVARCHAR (100)  NULL,
    [WheelBase]           NVARCHAR (100)  NULL,
    [TransmissionType]    NVARCHAR (50)   NULL,
    [NoGears]             INT             NULL,
    [Cooling]             NVARCHAR (100)  NULL,
    [CylConfiguration]    NVARCHAR (50)   NULL,
    [EngineCycle]         INT             NULL,
    [FuelTankSize]        DECIMAL (18, 2) NULL,
    [FuelType]            NVARCHAR (50)   NULL,
    [TurboOrSuperCharged] NVARCHAR (50)   NULL,
    [GCM]                 INT             NULL,
    [GVM]                 INT             NULL,
    [Tare]                INT             NULL,
    [Origin]              NVARCHAR (50)   NULL,
    [FrontNoTyres]        INT             NULL,
    [FrontTyreSize]       NVARCHAR (50)   NULL,
    [RearNoTyres]         INT             NULL,
    [RearTyreSize]        NVARCHAR (50)   NULL,
    [CO2]                 INT             NULL,
    [Length]              INT             NULL,
    [Height]              INT             NULL,
    [Width]               INT             NULL,
    [NewListPrice]        DECIMAL (18, 2) NULL,
    [SequenceNumber]      BIGINT          NOT NULL);

