CREATE TYPE [dbo].[VehicleUAESchemaV1] AS TABLE (
    [Id]             BIGINT         NOT NULL,
    [Manufacturer]   NVARCHAR (100) NULL,
    [Model]          NVARCHAR (100) NULL,
    [Variant]        NVARCHAR (100) NULL,
    [Trim]           NVARCHAR (100) NULL,
    [ModelYear]      INT            NULL,
    [Transmission]   NVARCHAR (100) NULL,
    [BodyType]       NVARCHAR (100) NULL,
    [FuelType]       NVARCHAR (100) NULL,
    [EngineCapacity] INT            NULL,
    [Doors]          NVARCHAR (100) NULL,
    [Cylinders]      INT            NULL,
    [Weight]         INT            NULL,
    [EnginePower]    NVARCHAR (100) NULL,
    [VehicleType]    NVARCHAR (100) NULL,
    [CountryId]      BIGINT         NULL,
    [IsActive]       BIT            NOT NULL,
    [CreatedDate]    DATE           NOT NULL,
    [ModifiedDate]   DATE           NULL,
    [CreatedBy]      INT            NOT NULL,
    [ModifiedBy]     INT            NULL,
    [SequenceNumber] BIGINT         NOT NULL);

