CREATE TYPE [dbo].[VehicleSchema] AS TABLE (
    [Id]               BIGINT         NOT NULL,
    [VehicleCode]      NVARCHAR (100) NULL,
    [ManufacturerId]   BIGINT         NULL,
    [Model]            NVARCHAR (100) NULL,
    [VehicleTypeId]    BIGINT         NULL,
    [BodyTypeId]       BIGINT         NULL,
    [IntroductionDate] DATE           NULL,
    [ModelYear]        INT            NULL,
    [TerminationDate]  DATE           NULL,
    [EngineCapacity]   INT            NULL,
    [EnginePower]      NVARCHAR (100) NULL,
    [Cylinders]        INT            NULL,
    [Doors]            INT            NULL,
    [CountryId]        BIGINT         NULL,
    [IsActive]         BIT            NOT NULL,
    [CreatedDate]      DATE           NOT NULL,
    [ModifiedDate]     DATE           NULL,
    [CreatedBy]        INT            NOT NULL,
    [ModifiedBy]       INT            NULL,
    [SequenceNumber]   BIGINT         NOT NULL);

