CREATE TABLE [dbo].[TransactionHistory](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ApplicationHistoryId] [bigint] NOT NULL,
	[TransactionId] [bigint] NOT NULL,
	[GroupId] [bigint] NOT NULL,
	[BranchId] [bigint] NOT NULL,
	[TransactionTypeId] [bigint] NULL,
	[TransactionStatusId] [bigint] NULL,
	[TransactionStatusNotes] [nvarchar](4000) NULL,
	[FinanceStatusId] [bigint] NULL,
	[FinanceStatusNotes] [nvarchar](4000) NULL,
	[IsDealSighted] [bit] NOT NULL,
	[SalesCompanyId] [bigint] NULL,
	[SalesReferenceNumber] [nvarchar](100) NULL,
	[SalesPersonId] [bigint] NULL,
	[BusinessManagerId] [int] NULL,
	[CompanyType] [bigint] NULL,
	[IsCashTransaction] [bit] NOT NULL,
	[PreferredInterestRate] [decimal](18, 2) NULL,
	[FinanceCompanyId] [bigint] NULL,
	[IsPreArrangedFinance] [bit] NOT NULL,
	[FinanceAccountNumber] [nvarchar](100) NULL,
	[FinanceTermId] [bigint] NULL,
	[VehicleId] [bigint] NULL,
	[VehicleUse] [bigint] NULL,
	[VehicleCondition] [bigint] NULL,
	[VehicleRegistrationName] [nvarchar](100) NULL,
	[VehicleRegisteredAt] [nvarchar](100) NULL,
	[ValuationDate] [date] NULL,
	[Valuator] [nvarchar](100) NULL,
	[DisburseId] [bigint] NULL,
	[PrivateKey] [nvarchar](100) NULL,
	[IsAssetInsured] [bit] NULL,
	[RetailPrice] [decimal](18, 2) NULL,
	[Discount] [decimal](18, 2) NULL,
	[TotalDeposit] [decimal](18, 2) NULL,
	[BalloonValue] [decimal](18, 2) NULL,
	[BalloonPercentage] [decimal](18, 2) NULL,
	[IsTradeIn] [bit] NULL,
	[IsTradeInCashTransaction] [bit] NULL,
	[TradeInFinanceCompanyId] [bigint] NULL,
	[TradeInCarFinanceAccNumber] [nvarchar](100) NULL,
	[TradeInCurrentInstalment] [decimal](18, 2) NULL,
	[TradeInValue] [decimal](18, 2) NULL,
	[TradeInSettlementValue] [decimal](18, 2) NULL,
	[TradeInCashPayback] [decimal](18, 2) NULL,
	[NetTradeInDepositValue] [decimal](18, 2) NULL,
	[TransactionClientId] [bigint] NULL,
	[TransactionDriverId] [bigint] NULL,
	[ChassisNumber] [nvarchar](100) NULL,
	[EngineNumber] [nvarchar](100) NULL,
	[RegistrationNumber] [nvarchar](100) NULL,
	[FirstRegistrationDate] [datetime] NULL,
	[Color] [nvarchar](50) NULL,
	[VehicleEmirate] [bigint] NULL,
	[DownPayment] [decimal](18, 2) NULL,
	[CountryId] [bigint] NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
	[CreatedBy] [int] NOT NULL,
	[ModifiedBy] [int] NULL,
	[InterestRateTypeId] [bigint] NULL,
	[PaymentType] [bigint] NULL,
	[ReferenceNumber] [nvarchar](50) NULL,
	[OdometerReading] [int] NULL,
	[FinanceType] [bigint] NULL,
	[SellingPrice] [decimal](18, 2) NULL,
	[VehicleCostPrice] [decimal](18, 2) NULL,
	[Immoblizer] [bigint] NULL,
	[IsManufacturerWarranty] [bit] NULL,
	[ManWarrantyExpiryMonths] [bigint] NULL,
	[ManWarrantyExpiryKM] [int] NULL,
	[ExistingWarranty] [bit] NULL,
	[ExistingWarrantyExpiryDate] [date] NULL,
	[ExistingWarrantyExpiryKM] [int] NULL,
	[ManufacturePlanType] [bigint] NULL,
	[ManPlanExpiryMonths] [bigint] NULL,
	[ManPlanExpiryKM] [int] NULL,
	[ExistingPlanType] [bigint] NULL,
	[ExistingPlanExpiryDate] [date] NULL,
	[ExistingPlanExpiryKM] [int] NULL,
	[IsIncepted] [bit] NOT NULL,
	[VehicleDescription] [nvarchar](200) NULL,
	[ProfitRate] [decimal](18, 2) NULL,
	[PreferredCallTime] [bigint] NULL,
	[VehicleTradeInValue] [decimal](18, 2) NULL,
	[IsManufaturerApprovedUsedVehicle] [bit] NULL,
	[IsFullServiceHistory] [bit] NULL,
	[Kilometers] [int] NULL,
	[VINNumber] [nvarchar](50) NULL,
	[TransactionNo] [bigint] NULL,
	[InceptDate] [datetime] NULL,
	[BankDocumentationFees] [decimal](18, 2) NULL,
	[StampDutyFees] [decimal](18, 2) NULL,
	[CallBackCustomerDateTime] [datetime] NULL,
	[DeclineDateTime] [datetime] NULL,
	[TransactionAPIOwner] [int] NULL,
	[HFAId] [bigint] NULL,
	[DocInvoiceNo] [nvarchar](50) NULL,
	[StockNo] [nvarchar](50) NULL,
	[DocInvoiceDate] [datetime] NULL,
	[DocInvoicePaidDate] [datetime] NULL,
	[VehicleDeliveryDate] [datetime] NULL,
	[OtherFee] [decimal](18, 2) NULL,
	[OtherCost] [decimal](18, 2) NULL,
	[DICAmount] [decimal](18, 2) NULL,
	[DICPercentage] [decimal](18, 2) NULL,
	[PayOutRequestDate] [datetime] NULL,
	[TransactionSource] [nvarchar](100) NULL,
	[SeatingCapacity] [int] NULL,
	[PrimeInterestRate] [decimal](18, 2) NULL,
	[IsBlockAutomaticUpdate] [bit] NULL,
	[APICompanyId] [bigint] NULL,
	[IsApiUpdate] [bit] NULL,
	[FleetNumber] [nvarchar](max) NULL,
	[BusinessSegment] [bigint] NULL,
	[ParentTransactionId] [bigint] NULL,
	[TransactionFee] [decimal](18, 2) NULL,
	[LOIIssueDate] [datetime] NULL,
	[LOIExpiryDate] [datetime] NULL,
	[LocalPurchaseNumber] [nvarchar](200) NULL,
	[LOPIssueDate] [datetime] NULL,
	[LOPExpiryDate] [datetime] NULL,
	[CopiedFrom] [nvarchar](max) NULL,
	[Scheme] [nvarchar](max) NULL,
 CONSTRAINT [PK_TransactionHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[TransactionHistory] ADD  DEFAULT ((0)) FOR [IsIncepted]
GO
ALTER TABLE [dbo].[TransactionHistory] ADD  CONSTRAINT [DF_TransactionHistory_IsBlockAutomaticUpdate]  DEFAULT ((0)) FOR [IsBlockAutomaticUpdate]
GO
ALTER TABLE [dbo].[TransactionHistory] ADD  CONSTRAINT [DF_TransactionHistory_IsApiUpdate]  DEFAULT ((0)) FOR [IsApiUpdate]