CREATE TABLE [dbo].[TransactionContactHistory](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[ApplicationHistoryId] [bigint] NOT NULL,
	[ContactId] [bigint] NOT NULL,
	[TransactionId] [bigint] NOT NULL,
	[Title] [bigint] NULL,
	[LastName] [nvarchar](100) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[MobileNumber] [nvarchar](50) NULL,
	[AlternativeMobileNumber] [nvarchar](50) NULL,
	[WorkTelephoneNumber] [nvarchar](100) NULL,
	[CountryId] [bigint] NULL,
	[IsActive] [bit] NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
	[CreatedBy] [int] NOT NULL,
	[ModifiedBy] [int] NULL,
	[RelationshipId] [bigint] NOT NULL,
	[SpouseEmployerName] [nvarchar](100) NULL,
	[SpouseEmployerAddress] [nvarchar](200) NULL,
	[SpouseOccupationId] [bigint] NULL,
	[PeriodOfEmployment] [nvarchar](50) NULL,
	[IsRegularDriver] [bit] NULL,
	[GenderId] [bigint] NULL,
	[Initials] [nvarchar](20) NULL,
	[HomePhoneCode] [nvarchar](20) NULL,
	[HomePhoneNumber] [nvarchar](50) NULL,
	[WorkPhoneCode] [nvarchar](20) NULL,
	[WorkPhoneNumber] [nvarchar](50) NULL,
	[IsSecondInsured] [bit] NOT NULL,
	[MiddleName] [nvarchar](100) NULL,
	[DriversLicenceNo] [nvarchar](100) NULL,
	[DriversLicenceIssueDate] [date] NULL,
	[DriversLicenceExpiryDate] [date] NULL,
	[DriversLicenceIssuePlace] [nvarchar](200) NULL,
	[Nationality] [bigint] NULL,
	[DateofBirth] [date] NULL,
	[PassportNo] [nvarchar](100) NULL,
	[PassportIssueDate] [date] NULL,
	[PassportExpiryDate] [date] NULL,
	[VisaNo] [nvarchar](100) NULL,
	[VisaIssueDate] [date] NULL,
	[VisaExpiryDate] [date] NULL,
	[EmiratesIdNo] [nvarchar](200) NULL,
	[EmiratesIdIssueDate] [date] NULL,
	[EmiratesIdExpiryDate] [date] NULL,
	[EmiratesIdIssuePlace] [nvarchar](200) NULL,
	[PhyAddBuildingName] [nvarchar](200) NULL,
	[PhyAddArea] [nvarchar](100) NULL,
	[PhyAddEmirate] [bigint] NULL,
	[PhyAddCountryId] [bigint] NULL,
	[PostAddPOBoxNo] [nvarchar](200) NULL,
	[PostAddEmirate] [bigint] NULL,
	[PostAddCountryId] [bigint] NULL,
	[ResidentialStatus] [bigint] NULL,
	[QualificationLevelId] [bigint] NULL,
	[EmailAddress] [nvarchar](100) NULL,
	[PhyAdd1] [nvarchar](200) NULL,
	[PhyAdd2] [nvarchar](200) NULL,
	[PhyAdd3] [nvarchar](200) NULL,
	[PostAdd1] [nvarchar](200) NULL,
	[PostAdd2] [nvarchar](200) NULL,
	[PostAdd3] [nvarchar](200) NULL,
	[IDNumber] [nvarchar](200) NULL,
	[IdIssueDate] [date] NULL,
	[IdExpiryDate] [date] NULL,
	[PermitNumber] [nvarchar](100) NULL,
	[PermitIssueDate] [date] NULL,
	[PermitExpiryDate] [date] NULL,
	[UAEResidentSince] [date] NULL,
	[Occupation] [nvarchar](200) NULL,
	[Designation] [nvarchar](200) NULL,
	[PhyAdd4] [nvarchar](200) NULL,
	[PhyAddCode] [nvarchar](100) NULL,
	[PostAdd4] [nvarchar](200) NULL,
	[PostAddCode] [nvarchar](100) NULL,
	[LanguageId] [bigint] NULL,
	[ConditionsOfResidentsPermit] [nvarchar](500) NULL,
	[MaritalStatusId] [bigint] NULL,
	[MarriageDate] [date] NULL,
	[NoofDependents] [int] NULL,
	[MarrageTypeId] [bigint] NULL,
	[SpecifyMaritalStatus] [nvarchar](100) NULL,
	[NoOfYearsAtPesentAddress] [int] NULL,
	[NoOfMonthsAtPesentAddress] [int] NULL,
	[PreferedMailingAddress] [bigint] NULL,
	[PreferedContactMethod] [bigint] NULL,
	[CountryOfBirth] [bigint] NULL,
	[PreviousAdd1] [nvarchar](200) NULL,
	[PreviousAdd2] [nvarchar](200) NULL,
	[PreviousAdd3] [nvarchar](200) NULL,
	[PreviousAdd4] [nvarchar](50) NULL,
	[PreviousAddCode] [nvarchar](100) NULL,
	[NoOfYearsAtPreviousAddress] [int] NULL,
	[NoOfMonthsAtPreviousAddress] [int] NULL,
	[IsDualCitizenship] [bit] NULL,
	[DualCitizenshipCountryId] [bigint] NULL,
	[HomeCountryId] [bigint] NULL,
	[AddressInHomeCountry] [nvarchar](500) NULL,
	[ContactNumberInHomeCountry] [nvarchar](50) NULL,
	[ShareholdingPercentage] [decimal](18, 2) NULL,
	[IsOwnHome] [bit] NULL,
	[HomeCountryAddress1] [nvarchar](200) NULL,
	[HomeCountryAddress2] [nvarchar](200) NULL,
	[HomeCountryAddress3] [nvarchar](200) NULL,
	[HomeCountryAddress4] [nvarchar](200) NULL,
	[HomeCountryAddressCode] [nvarchar](100) NULL,
	[IsContract] [bit] NULL,
	[IsSurety] [bit] NULL,
	[IsThirdPartyRegistration] [bit] NULL,
	[JoiningDate] [date] NULL,
	[MakaniNumber] [nvarchar](200) NULL,
	[TradeLicenseNumber] [nvarchar](200) NULL,
	[TradelicenseExpiryDate] [date] NULL,
	[DateofInception] [date] NULL,
	[EmploymentCategoryId] [bigint] NULL,
	[PhyAddNearestLandMark] [nvarchar](200) NULL,
	[FaxCode] [nvarchar](10) NULL,
	[FaxNumber] [nvarchar](50) NULL,
 CONSTRAINT [PK_TransactionContactHistory] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TransactionContactHistory] ADD  DEFAULT ((0)) FOR [IsRegularDriver]
GO
ALTER TABLE [dbo].[TransactionContactHistory] ADD  DEFAULT ((0)) FOR [IsSecondInsured]