CREATE TABLE [dbo].[HFAItemVehicleDetails](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[CountryId] [bigint] NULL,
	[BranchId] [bigint] NULL,
	[IsHFADeclaration] [bit] NULL,
	[ItemDescription] [nvarchar](2000) NULL,
	[ItemSerialNumber] [nvarchar](100) NULL,
	[ItemCode] [nvarchar](100) NULL,
	[ItemRetailValue] [decimal](18, 8) NULL,
	[ItemQuantity] [int] NULL,
	[Notes] [nvarchar](2000) NULL,
	[VehicleId] [bigint] NULL,
	[VehicleCondition] [bigint] NULL,
	[VehicleUse] [bigint] NULL,
	[RetailPrice] [decimal](18, 8) NULL,
	[DownPayment] [decimal](18, 8) NULL,
	[VehicleDescription] [nvarchar](200) NULL,
	[TitleId] [bigint] NULL,
	[FirstName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
	[GenderId] [bigint] NULL,
	[IDNumber] [nvarchar](100) NULL,
	[PassportNo] [nvarchar](100) NULL,
	[Mobile] [nvarchar](100) NULL,
	[DateofBirth] [date] NULL,
	[EmailAddress] [nvarchar](100) NULL,
	[EmploymentTypeId] [bigint] NULL,
	[NameofEmployer] [nvarchar](200) NULL,
	[JoiningDate] [date] NULL,
	[GrossMonthlySalary] [decimal](18, 8) NULL,
	[MonthlySalary] [decimal](18, 8) NULL,
	[OtherIncome] [decimal](18, 8) NULL,
	[BankId] [bigint] NULL,
	[BranchName] [nvarchar](200) NULL,
	[BranchCode] [nvarchar](50) NULL,
	[AccountType] [bigint] NULL,
	[IsDeclaredInsolvent] [bit] NULL,
	[IsUnderDebtReview] [bit] NULL,
	[IsGuarantorsDetails] [bit] NULL,
	[IsShareholderInCompany] [bit] NULL,
	[IsCustomerBankStatement] [bit] NULL,
	[IsShareDetailsWithinCompany] [bit] NULL,
	[IsShareDetailsAmongPartner] [bit] NULL,
	[IsReceiveMarketingInfo] [bit] NULL,
	[IsSubmit] [bit] NULL,
	[IsUnsecuredTransaction] [bit] NULL,
	[EmiratesIDNumber] [nvarchar](100) NULL,
	[AccountNo] [nvarchar](200) NULL,
	[PreferredCallTime] [bigint] NULL,
	[CustomerType] [int] NULL,
	[CompanyName] [nvarchar](100) NULL,
	[ComNatureOfBusiness] [bigint] NULL,
	[ComVATNumber] [nvarchar](50) NULL,
	[ComRegistrationNumber] [nvarchar](50) NULL,
	[BusinessTypeId] [bigint] NULL,
	[BusinessName] [nvarchar](200) NULL,
	[DateofInception] [date] NULL,
	[TradeLicenceNo] [nvarchar](200) NULL,
	[TradeLicenceExpiryDate] [date] NULL,
	[TotalExpenses] [decimal](18, 8) NULL,
	[LastSavedDateTime] [datetime] NULL,
	[HFAResumeOTP] [int] NULL,
	[ResumeHFATab] [varchar](100) NULL,
	[HFAReferenceNumber] [nvarchar](100) NULL,
 CONSTRAINT [PK_HFAItemVehicleDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]