CREATE TABLE [dbo].[InceptTransactionClient](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NULL,
	[MiddleName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
	[Initials] [nvarchar](50) NULL,
	[DateofBirth] [date] NULL,
	[PlaceOfBirth] [nvarchar](200) NULL,
	[Nationality] [bigint] NULL,
	[NoofDependents] [int] NULL,
	[MarriageDate] [date] NULL,
	[MothersMaidenName] [nvarchar](200) NULL,
	[UAEResidentSince] [date] NULL,
	[IDNumber] [nvarchar](100) NULL,
	[PassportNo] [nvarchar](100) NULL,
	[PassportIssueDate] [date] NULL,
	[PassportExpiryDate] [date] NULL,
	[PassportIssuePlace] [nvarchar](200) NULL,
	[VisaNo] [nvarchar](100) NULL,
	[VisaIssueDate] [date] NULL,
	[VisaExpiryDate] [date] NULL,
	[VisaIssuePlace] [nvarchar](200) NULL,
	[EmiratesIdNo] [nvarchar](200) NULL,
	[EmiratesIdIssueDate] [date] NULL,
	[EmiratesIdExpiryDate] [date] NULL,
	[EmiratesIdIssuePlace] [nvarchar](200) NULL,
	[DriversLicenceNo] [nvarchar](100) NULL,
	[DriversLicenceIssueDate] [date] NULL,
	[DriversLicenceExpiryDate] [date] NULL,
	[DriversLicenceIssuePlace] [nvarchar](200) NULL,
	[UAEDrivingLicenceNo] [nvarchar](100) NULL,
	[PreferredName] [nvarchar](100) NULL,
	[Mobile] [nvarchar](100) NULL,
	[AlternativeMobile] [nvarchar](100) NULL,
	[HomePhoneCode] [nvarchar](10) NULL,
	[HomePhoneNumber] [nvarchar](50) NULL,
	[WorkPhoneCode] [nvarchar](10) NULL,
	[WorkPhoneNumber] [nvarchar](50) NULL,
	[FaxCode] [nvarchar](10) NULL,
	[FaxNumber] [nvarchar](50) NULL,
	[ContactNumberInHomeCountry] [nvarchar](50) NULL,
	[EmailAddress] [nvarchar](100) NULL,
	[IsSMSAlertRequired] [bit] NULL,
	[PreferedMailingAddress] [int] NULL,
	[NumberForSMSAlert] [nvarchar](100) NULL,
	[PhyAddBuildingName] [nvarchar](200) NULL,
	[PhyAddFlatNo] [nvarchar](50) NULL,
	[PhyAddUnitNo] [nvarchar](50) NULL,
	[PhyAddNearestLandmark] [nvarchar](200) NULL,
	[PhyAddArea] [nvarchar](100) NULL,
	[PhyAddStreetName] [nvarchar](200) NULL,
	[PostAddPOBoxNo] [nvarchar](200) NULL,
	[PhyAddEmirate] [bigint] NULL,
	[PhyAddCity] [nvarchar](200) NULL,
	[PhyAddState] [nvarchar](100) NULL,
	[PhyAddZipCode] [nvarchar](50) NULL,
	[PostAddEmirate] [bigint] NULL,
	[ResidentialStatus] [bigint] NULL,
	[NoOfYearsAtPesentAddress] [nvarchar](50) NULL,
	[RentPerMonth] [decimal](18, 2) NULL,
	[AddressInHomeCountry] [nvarchar](500) NULL,
	[CustomerType] [int] NULL,
	[NameOfKin] [nvarchar](100) NULL,
	[AddressOfKin] [nvarchar](200) NULL,
	[ContactOfKin] [nvarchar](50) NULL,
	[CountryId] [bigint] NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
	[CreatedBy] [int] NOT NULL,
	[ModifiedBy] [int] NULL,
	[TitleId] [bigint] NULL,
	[TitleValue] [nvarchar](50) NULL,
	[MaritalStatusId] [bigint] NULL,
	[MaritalStatusValue] [nvarchar](50) NULL,
	[GenderId] [bigint] NULL,
	[GenderValue] [nvarchar](50) NULL,
	[IDTypeId] [bigint] NULL,
	[IDTypeValue] [nvarchar](50) NULL,
	[PhyAddCountryId] [bigint] NULL,
	[PhyAddCountryValue] [nvarchar](50) NULL,
	[PostAddCountryId] [bigint] NULL,
	[PostAddCountryValue] [nvarchar](50) NULL,
	[HomeCountryId] [bigint] NULL,
	[HomeCountryValue] [nvarchar](50) NULL,
	[BankingDetailsId] [bigint] NULL,
	[CustomerTypeValue] [nvarchar](50) NULL,
	[CountryValue] [nvarchar](50) NULL,
	[CreatedByValue] [nvarchar](50) NULL,
	[ModifiedByValue] [nvarchar](50) NULL,
	[InceptTransactionId] [bigint] NOT NULL,
	[TransactionId] [bigint] NOT NULL,
	[IsGuarantorApplication] [bit] NULL,
	[RegularDriver] [bit] NULL,
	[ConditionsResidentPermit] [nvarchar](100) NULL,
	[LanguageId] [bigint] NULL,
	[LanguageValue] [nvarchar](50) NULL,
	[MarrageTypeId] [bigint] NULL,
	[MarrageTypeValue] [nvarchar](50) NULL,
	[SpousesName] [nvarchar](100) NULL,
	[SpousesBirthDate] [date] NULL,
	[PhyAddSurburb] [nvarchar](50) NULL,
	[PhyAddTown] [nvarchar](50) NULL,
	[PostAddSurburb] [nvarchar](50) NULL,
	[PostAddTown] [nvarchar](50) NULL,
	[SpecifyResidentialStatus] [nvarchar](100) NULL,
	[PreviousHomeAddress] [nvarchar](100) NULL,
	[PreferredCallTime] [bigint] NULL,
	[PreferredCallTimeValue] [nvarchar](50) NULL,
	[NationalityValue] [nvarchar](50) NULL,
	[ResidentialStatusValue] [nvarchar](50) NULL,
	[CompanyName] [nvarchar](max) NULL,
	[ComNatureOfBusiness] [bigint] NULL,
	[ComNatureOfBusinessValue] [nvarchar](50) NULL,
	[CompanyStartDate] [date] NULL,
	[ComTradeLicenceStartDate] [date] NULL,
	[ComTradeLicenceExpiryDate] [date] NULL,
	[ComVATNumber] [nvarchar](50) NULL,
	[ComPhyAddBuildingName] [nvarchar](200) NULL,
	[ComPhyAddStreetName] [nvarchar](100) NULL,
	[ComPhyAddEmirate] [bigint] NULL,
	[ComPhyAddPostCode] [nvarchar](100) NULL,
	[ComPhyAddCountryId] [bigint] NULL,
	[ComPhyAddCountryValue] [nvarchar](50) NULL,
	[ComTradingAs] [nvarchar](50) NULL,
	[ComRegistrationNumber] [nvarchar](50) NULL,
	[ComNoOfYearsInBusiness] [int] NULL,
	[ComLandlord] [nvarchar](100) NULL,
	[ComHoldingCompany] [nvarchar](100) NULL,
	[ComAssociatedCompany] [nvarchar](200) NULL,
	[ComSubsidaryCompany] [nvarchar](200) NULL,
	[ComCompanyRepresentative] [nvarchar](100) NULL,
	[ComFloorNo] [int] NULL,
	[ComYearsAtCurrentAddress] [int] NULL,
	[ComEmirate] [bigint] NULL,
	[PhyAdd1] [nvarchar](200) NULL,
	[PhyAdd2] [nvarchar](200) NULL,
	[PhyAdd3] [nvarchar](200) NULL,
	[PostAdd1] [nvarchar](200) NULL,
	[PostAdd2] [nvarchar](200) NULL,
	[PostAdd3] [nvarchar](200) NULL,
	[FinanceStatus] [bigint] NULL,
	[FinanceStatusValue] [nvarchar](50) NULL,
	[FinanceStatusNotes] [nvarchar](500) NULL,
	[ConditionsOfResidentsPermit] [nvarchar](500) NULL,
	[BusinessTypeId] [bigint] NULL,
	[BusinessTypeValue] [nvarchar](50) NULL,
	[QualificationId] [bigint] NULL,
	[QualificationValue] [nvarchar](50) NULL,
	[PhyAddEmirateValue] [nvarchar](50) NULL,
	[PostAddEmirateValue] [nvarchar](100) NULL,
	[ComPhyAddEmirateValue] [nvarchar](100) NULL,
	[ComEmirateValue] [nvarchar](50) NULL,
	[PermitNumber] [nvarchar](100) NULL,
	[PermitIssueDate] [date] NULL,
	[PermitExpiryDate] [date] NULL,
	[IdIssueDate] [date] NULL,
	[IdExpiryDate] [date] NULL,
	[SpecifyMaritalStatus] [nvarchar](100) NULL,
	[EthnicGroup] [bigint] NULL,
	[EthnicGroupValue] [nvarchar](200) NULL,
	[NoOfMonthsAtPesentAddress] [nvarchar](50) NULL,
	[MarketingSource] [bigint] NULL,
	[MarketingSourceValue] [nvarchar](200) NULL,
	[ClaimFreeGroup] [bigint] NULL,
	[ClaimFreeGroupValue] [nvarchar](50) NULL,
	[IsCompanyVATRegistered] [bit] NULL,
	[PhyAdd4] [nvarchar](200) NULL,
	[PhyAddCode] [nvarchar](100) NULL,
	[PostAdd4] [nvarchar](200) NULL,
	[PostAddCode] [nvarchar](100) NULL,
	[IsCompanyBlackOwned] [bit] NULL,
	[IsCompanyBalanceSheet] [bit] NULL,
	[CompanyFinancialYear] [nvarchar](200) NULL,
	[CompanyTurnover] [decimal](18, 4) NULL,
	[CompanyTotalAssets] [decimal](18, 4) NULL,
	[ComPhyAdd1] [nvarchar](200) NULL,
	[ComPhyAdd2] [nvarchar](200) NULL,
	[ComPhyAdd3] [nvarchar](200) NULL,
	[ComPhyAdd4] [nvarchar](200) NULL,
	[ComPhyAddCode] [nvarchar](100) NULL,
	[HomeCountryAddress1] [nvarchar](200) NULL,
	[HomeCountryAddress2] [nvarchar](200) NULL,
	[HomeCountryAddress3] [nvarchar](200) NULL,
	[HomeCountryAddress4] [nvarchar](200) NULL,
	[HomeCountryAddressCode] [nvarchar](100) NULL,
	[PreferredLanguage] [nvarchar](200) NULL,
	[TradeLicenseNumber] [nvarchar](200) NULL,
	[IsSpouseDetailsIncluded] [bit] NULL,
	[ComPhyAddMakaniNumber] [nvarchar](200) NULL,
	[OfficeBuildingName] [nvarchar](200) NULL,
	[OfficeStreetName] [nvarchar](200) NULL,
	[OfficeEmirate] [bigint] NULL,
	[OfficeCountry] [bigint] NULL,
	[OfficeNearestLandmark] [nvarchar](200) NULL,
	[OfficeMakaniNumber] [nvarchar](200) NULL,
	[ComNumberofFleetVehicles] [bigint] NULL,
	[ComNumberofMortgagedVehicles] [bigint] NULL,
	[FamilyName] [nvarchar](200) NULL,
	[FirstNameInArabic] [nvarchar](200) NULL,
	[MiddleNameInArabic] [nvarchar](200) NULL,
	[LastNameInArabic] [nvarchar](200) NULL,
	[FamilyNameInArabic] [nvarchar](200) NULL,
	[IsResident] [bit] NULL,
	[ComNoOfPeopleEmployed] [int] NULL,
	[ComTradeLicensePlaceofIssue] [nvarchar](200) NULL,
	[AreaName] [nvarchar](200) NULL,
	[VillaOrApartmentNumber] [nvarchar](50) NULL,
	[AreaCodeId] [bigint] NULL,
	[OfficeTelephonenumberExtension] [nvarchar](10) NULL,
	[CityId] [bigint] NULL,
	[NewInCountry] [bit] NULL,
 CONSTRAINT [InceptTransactionClient_PK] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[InceptTransactionClient]  WITH NOCHECK ADD  CONSTRAINT [FK_InceptTransactionClient_InceptTransaction] FOREIGN KEY([InceptTransactionId])
REFERENCES [dbo].[InceptTransaction] ([Id])
GO

ALTER TABLE [dbo].[InceptTransactionClient] CHECK CONSTRAINT [FK_InceptTransactionClient_InceptTransaction]
GO
ALTER TABLE [dbo].[InceptTransactionClient]  WITH NOCHECK ADD  CONSTRAINT [InceptTransactionClient_FK_StaticValueAreaCodeId] FOREIGN KEY([AreaCodeId])
REFERENCES [dbo].[StaticValue] ([Id])
GO

ALTER TABLE [dbo].[InceptTransactionClient] CHECK CONSTRAINT [InceptTransactionClient_FK_StaticValueAreaCodeId]
GO
ALTER TABLE [dbo].[InceptTransactionClient]  WITH NOCHECK ADD  CONSTRAINT [InceptTransactionClient_FK_StaticValueCityId] FOREIGN KEY([CityId])
REFERENCES [dbo].[StaticValue] ([Id])
GO

ALTER TABLE [dbo].[InceptTransactionClient] CHECK CONSTRAINT [InceptTransactionClient_FK_StaticValueCityId]
GO
ALTER TABLE [dbo].[InceptTransactionClient] ADD  CONSTRAINT [DF_InceptTransactionClient_IsSMSAlertRequired]  DEFAULT ((0)) FOR [IsSMSAlertRequired]
GO
ALTER TABLE [dbo].[InceptTransactionClient] ADD  CONSTRAINT [InceptTransactionClient_DF_IsActive]  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[InceptTransactionClient] ADD  CONSTRAINT [InceptTransactionClient_DF_CreatedDate]  DEFAULT (getutcdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[InceptTransactionClient] ADD  DEFAULT ((0)) FOR [IsSpouseDetailsIncluded]