CREATE TABLE [dbo].[ApiLogEntry] (
    [Id]                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [Application]          NVARCHAR (100) NULL,
    [User]                 NVARCHAR (100) NULL,
    [Machine]              NVARCHAR (100) NULL,
    [RequestIpAddress]     NVARCHAR (100) NULL,
    [RequestContentType]   NVARCHAR (100) NULL,
    [RequestContentBody]   NVARCHAR (MAX) NULL,
    [RequestUri]           NVARCHAR (100) NULL,
    [RequestMethod]        NVARCHAR (100) NULL,
    [RequestRouteTemplate] NVARCHAR (100) NULL,
    [RequestRouteData]     NVARCHAR (MAX) NULL,
    [RequestHeaders]       NVARCHAR (MAX) NULL,
    [RequestTimestamp]     DATETIME       NULL,
    [ResponseContentType]  NVARCHAR (100) NULL,
    [ResponseContentBody]  NVARCHAR (MAX) NULL,
    [ResponseStatusCode]   INT            NULL,
    [ResponseHeaders]      NVARCHAR (MAX) NULL,
    [ResponseTimestamp]    DATETIME       NULL,
    [CreatedBy]            INT            NULL,
    [ModifiedBy]           INT            NULL,
    [CreatedDate]          DATETIME       NULL,
    [ModifiedDate]         DATETIME       NULL,
    [APIEnumType]          INT            CONSTRAINT [DF__ApiLogEnt__APIEn__2C316395] DEFAULT ((1)) NULL,
    CONSTRAINT [ApiLogEntry_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [ApiLogEntry_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [ApiLogEntry_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

