CREATE TABLE [dbo].[DealTrackerReportFilterMapping] (
    [Id]                             BIGINT   IDENTITY (1, 1) NOT NULL,
    [DealTrackerReportFilterId]      BIGINT   NOT NULL,
    [GroupId]                        BIGINT   NULL,
    [BranchId]                       BIGINT   NULL,
    [BusinessManagerId]              INT      NULL,
    [SalesPersonId]                  BIGINT   NULL,
    [FinanceCompanyId]               BIGINT   NULL,
    [CriteriaEnum]                   INT      NULL,
    [IsActive]                       BIT      DEFAULT ((0)) NOT NULL,
    [CreatedDate]                    DATETIME NULL,
    [ModifiedDate]                   DATETIME NULL,
    [CreatedBy]                      INT      NULL,
    [ModifiedBy]                     INT      NULL,
    [FinanceCompanyTakenUpId]        BIGINT   NULL,
    [IsFinanceCompanyTakenUpIdBlank] BIT      DEFAULT ((0)) NOT NULL,
    [IsFinanceCompanyIdBlank]        BIT      DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_DealTrackerReportFilterMapping] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_Branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[Branch] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_CompanyCompanyTypeMapping] FOREIGN KEY ([FinanceCompanyId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_CompanyCompanyTypeMapping1] FOREIGN KEY ([FinanceCompanyTakenUpId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_DealTrackerReportFilter] FOREIGN KEY ([DealTrackerReportFilterId]) REFERENCES [dbo].[DealTrackerReportFilter] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_SalesPerson] FOREIGN KEY ([SalesPersonId]) REFERENCES [dbo].[SalesPerson] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_Users] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_Users1] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_DealTrackerReportFilterMapping_Users2] FOREIGN KEY ([BusinessManagerId]) REFERENCES [dbo].[Users] ([Id])
);

