CREATE TABLE [dbo].[DOCReportFilterMapping] (
    [Id]                 BIGINT   IDENTITY (1, 1) NOT NULL,
    [DOCReportFilterId]  BIGINT   NULL,
    [GroupId]            BIGINT   NULL,
    [BranchId]           BIGINT   NULL,
    [BusinessManagerId]  INT      NULL,
    [SalesPersonId]      BIGINT   NULL,
    [FinanceCompanyId]   BIGINT   NULL,
    [TransactionTypeId]  BIGINT   NULL,
    [VehicleConditionId] BIGINT   NULL,
    [CriteriaEnum]       INT      NULL,
    [IsActive]           BIT      CONSTRAINT [DF__DOCReport__IsAct__694C5312] DEFAULT ((0)) NOT NULL,
    [CreatedDate]        DATETIME NULL,
    [ModifiedDate]       DATETIME NULL,
    [CreatedBy]          INT      NULL,
    [ModifiedBy]         INT      NULL,
    [SummaryPages]       BIGINT   NULL,
    [IsSummaryReport]    BIT      CONSTRAINT [DF__DOCReport__IsSum__71E3FB18] DEFAULT ((0)) NULL,
    CONSTRAINT [DOCReportFilterMapping_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [DOCReportFilterMapping_FK_Branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[Branch] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_CompanyCompanyTypeMapping] FOREIGN KEY ([FinanceCompanyId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_DOCReportFilter] FOREIGN KEY ([DOCReportFilterId]) REFERENCES [dbo].[DOCReportFilter] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_SalesPerson] FOREIGN KEY ([SalesPersonId]) REFERENCES [dbo].[SalesPerson] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_StaticValue] FOREIGN KEY ([SummaryPages]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_StaticValueTransactionTypeId] FOREIGN KEY ([TransactionTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_StaticValueVehicleConditionId] FOREIGN KEY ([VehicleConditionId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_UsersBusinessManagerId] FOREIGN KEY ([BusinessManagerId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [DOCReportFilterMapping_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

