CREATE TABLE [dbo].[FinanceApplicationHistory] (
    [id]                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [TransactionID]        BIGINT         NOT NULL,
    [FinanceApplicationID] BIGINT         NOT NULL,
    [CompanyCompanyTypeID] BIGINT         NOT NULL,
    [AppType]              NVARCHAR (50)  NULL,
    [RequestURL]           NVARCHAR (MAX) NULL,
    [Action]               NVARCHAR (MAX) NULL,
    [LeadNumber]           BIGINT         NULL,
    [LeadStatus]           BIGINT         NULL,
    [Response]             NVARCHAR (MAX) NULL,
    [ServiceMessage]       NVARCHAR (MAX) NULL,
    [RequestFilePath]      NVARCHAR (MAX) NULL,
    [ResponseFilePath]     NVARCHAR (MAX) NULL,
    [RequestTimeStamp]     DATETIME       NULL,
    [ResponseTimeStamp]    DATETIME       NULL,
    [DocumentName]         NVARCHAR (MAX) NULL,
    [ResponseStatusIds]    NVARCHAR (MAX) NULL,
    [LoanAmount]           NVARCHAR (10)  NULL,
    [LoanTerm]             NVARCHAR (10)  NULL,
    [LoanDeposit]          NVARCHAR (50)  NULL,
    [LoanInterest]         NVARCHAR (10)  NULL,
    [isActive]             BIT            CONSTRAINT [DF__FinanceAp__isAct__573004DC] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_FinanceApplicationHistory] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_FinanceApplicationHistory_CompanyCompanyTypeID] FOREIGN KEY ([CompanyCompanyTypeID]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_FinanceApplicationHistory_FinanceApplicationID] FOREIGN KEY ([FinanceApplicationID]) REFERENCES [dbo].[TransactionFinanceApplication] ([Id]),
    CONSTRAINT [FK_FinanceApplicationHistory_TransactionID] FOREIGN KEY ([TransactionID]) REFERENCES [dbo].[Transaction] ([Id])
);

