CREATE TABLE [dbo].[GlobalSettings] (
    [Id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [ContactEmailAddress]  NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [ContactEmailPassword] NVARCHAR (MAX)  COLLATE Latin1_General_CI_AS NULL,
    [VatPercentage]        DECIMAL (18, 2) NULL,
    [SalesTax]             DECIMAL (18, 2) NULL,
    [Currency]             NVARCHAR (50)   NULL,
    [CurrencySymbol]       NVARCHAR (50)   NULL,
    [MakaniNumber]         NVARCHAR (100)  NULL,
    [BankLendingRate]      DECIMAL (18, 2) NULL,
    [CountryId]            BIGINT          NULL,
    [IsActive]             BIT             CONSTRAINT [DF_GlobalSettings_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]          DATETIME        CONSTRAINT [DF_GlobalSettings_CreatedDate] DEFAULT (getutcdate()) NULL,
    [ModifiedDate]         DATETIME        NULL,
    [CreatedBy]            INT             NULL,
    [ModifiedBy]           INT             NULL,
    [SMTPHost]             NVARCHAR (100)  NULL,
    [SMTPPort]             NVARCHAR (100)  NULL,
    [FromEmail]            NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [APINotificationEmail] NVARCHAR (4000) COLLATE Latin1_General_CI_AS NULL,
    [Namfisa]              DECIMAL (18, 2) NULL,
    [StampDuty]            DECIMAL (18, 2) NULL,
    [PrimeInterestRate]    DECIMAL (18, 2) NULL,
    CONSTRAINT [GlobalSettings_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [GlobalSettings_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [GlobalSettings_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [GlobalSettings_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

