CREATE TABLE [dbo].[HFAItemVehicleDetails] (
    [Id]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [CountryId]                   BIGINT          NULL,
    [BranchId]                    BIGINT          NULL,
    [IsHFADeclaration]            BIT             NULL,
    [ItemDescription]             NVARCHAR (2000) NULL,
    [ItemSerialNumber]            NVARCHAR (100)  NULL,
    [ItemCode]                    NVARCHAR (100)  NULL,
    [ItemRetailValue]             DECIMAL (18, 8) NULL,
    [ItemQuantity]                INT             NULL,
    [Notes]                       NVARCHAR (2000) NULL,
    [VehicleId]                   BIGINT          NULL,
    [VehicleCondition]            BIGINT          NULL,
    [VehicleUse]                  BIGINT          NULL,
    [RetailPrice]                 DECIMAL (18, 8) NULL,
    [DownPayment]                 DECIMAL (18, 8) NULL,
    [VehicleDescription]          NVARCHAR (200)  NULL,
    [TitleId]                     BIGINT          NULL,
    [FirstName]                   NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [LastName]                    NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [GenderId]                    BIGINT          NULL,
    [IDNumber]                    NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PassportNo]                  NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [Mobile]                      NVARCHAR (100)  NULL,
    [DateofBirth]                 DATE            NULL,
    [EmailAddress]                NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [EmploymentTypeId]            BIGINT          NULL,
    [NameofEmployer]              NVARCHAR (200)  NULL,
    [JoiningDate]                 DATE            NULL,
    [GrossMonthlySalary]          DECIMAL (18, 8) NULL,
    [MonthlySalary]               DECIMAL (18, 8) NULL,
    [OtherIncome]                 DECIMAL (18, 8) NULL,
    [BankId]                      BIGINT          NULL,
    [BranchName]                  NVARCHAR (200)  NULL,
    [BranchCode]                  NVARCHAR (50)   NULL,
    [AccountType]                 BIGINT          NULL,
    [IsDeclaredInsolvent]         BIT             NULL,
    [IsUnderDebtReview]           BIT             NULL,
    [IsGuarantorsDetails]         BIT             NULL,
    [IsShareholderInCompany]      BIT             NULL,
    [IsCustomerBankStatement]     BIT             NULL,
    [IsShareDetailsWithinCompany] BIT             NULL,
    [IsShareDetailsAmongPartner]  BIT             NULL,
    [IsReceiveMarketingInfo]      BIT             NULL,
    [IsSubmit]                    BIT             NULL,
    [IsUnsecuredTransaction]      BIT             NULL,
    [EmiratesIDNumber]            NVARCHAR (100)  COLLATE Latin1_General_BIN2 NULL,
    [AccountNo]                   NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [PreferredCallTime]           BIGINT          NULL,
    [CustomerType]                INT             NULL,
    [CompanyName]                 NVARCHAR (100)  NULL,
    [ComNatureOfBusiness]         BIGINT          NULL,
    [ComVATNumber]                NVARCHAR (50)   NULL,
    [ComRegistrationNumber]       NVARCHAR (50)   NULL,
    [BusinessTypeId]              BIGINT          NULL,
    [BusinessName]                NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [DateofInception]             DATE            NULL,
    [TradeLicenceNo]              NVARCHAR (200)  NULL,
    [TradeLicenceExpiryDate]      DATE            NULL,
    [TotalExpenses]               DECIMAL (18, 8) NULL,
    [LastSavedDateTime]           DATETIME        NULL,
    [HFAResumeOTP]                INT             NULL,
    [ResumeHFATab]                VARCHAR (100)   NULL,
    [HFAReferenceNumber]          NVARCHAR (100)  NULL,
    CONSTRAINT [PK_HFAItemVehicleDetails] PRIMARY KEY CLUSTERED ([Id] ASC)
);

