CREATE TABLE [dbo].[InceptTransactionItem] (
    [Id]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [TransactionId]         BIGINT          NULL,
    [InceptTransactionId]   BIGINT          NULL,
    [ItemTypeId]            BIGINT          NULL,
    [ItemTypeValue]         NVARCHAR (500)  NULL,
    [ItemUseId]             BIGINT          NULL,
    [ItemUseValue]          NVARCHAR (500)  NULL,
    [ItemDescription]       NVARCHAR (2000) NULL,
    [ItemCode]              NVARCHAR (100)  NULL,
    [ItemSerialNumber]      NVARCHAR (100)  NULL,
    [ItemCost]              DECIMAL (18, 8) NULL,
    [ItemRetailValue]       DECIMAL (18, 8) NULL,
    [ItemQuantity]          INT             NULL,
    [TotalItemsRetailValue] DECIMAL (18, 8) NULL,
    [LoanAmountAppliedFor]  DECIMAL (18, 8) NULL,
    [Discount]              DECIMAL (18, 8) NULL,
    [Notes]                 NVARCHAR (2000) NULL,
    [IsActive]              BIT             CONSTRAINT [DF_InceptTransactionItem_IsActive] DEFAULT ((1)) NOT NULL,
    [CountryId]             BIGINT          NULL,
    [CountryValue]          NVARCHAR (500)  NULL,
    [CreatedBy]             INT             NULL,
    [CreatedByValue]        NVARCHAR (500)  NULL,
    [ModifiedBy]            INT             NULL,
    [ModifiedByValue]       NVARCHAR (500)  NULL,
    [CreatedDate]           DATETIME        CONSTRAINT [DF_InceptTransactionItem_CreatedDate] DEFAULT (getutcdate()) NULL,
    [ModifiedDate]          DATETIME        NULL,
    [MaxLoanApproved]       DECIMAL (18, 8) NULL,
    [ItemInvoiceNo]         NVARCHAR (50)   NULL,
    [ItemStockNo]           NVARCHAR (50)   NULL,
    [ItemInvoiceDate]       DATETIME        NULL,
    [ItemInvoicePaidDate]   DATETIME        NULL,
    [ItemDeliveryDate]      DATETIME        NULL,
    [Deposit]               DECIMAL (18, 8) NULL,
    CONSTRAINT [InceptTransactionItem_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [InceptTransactionItem_FK_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id])
);

