CREATE TABLE [dbo].[InceptTransactionContact] (
    [Id]                             BIGINT         NOT NULL,
    [TransactionId]                  BIGINT         NOT NULL,
    [Title]                          BIGINT         NULL,
    [TitleValue]                     NVARCHAR (50)  NULL,
    [LastName]                       NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [FirstName]                      NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [MobileNumber]                   NVARCHAR (50)  NULL,
    [AlternativeMobileNumber]        NVARCHAR (50)  NULL,
    [WorkTelephoneNumber]            NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [RelationshipId]                 BIGINT         NULL,
    [RelationshipValue]              NVARCHAR (50)  NULL,
    [SpouseEmployerName]             NVARCHAR (100) NULL,
    [SpouseEmployerAddress]          NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [SpouseOccupationId]             BIGINT         NULL,
    [SpouseOccupationValue]          NVARCHAR (50)  NULL,
    [PeriodOfEmployment]             NVARCHAR (50)  NULL,
    [IsRegularDriver]                BIT            DEFAULT ((0)) NULL,
    [GenderId]                       BIGINT         NULL,
    [GenderValue]                    NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL,
    [Initials]                       NVARCHAR (20)  NULL,
    [HomePhoneCode]                  NVARCHAR (20)  COLLATE Latin1_General_CI_AS NULL,
    [HomePhoneNumber]                NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneCode]                  NVARCHAR (20)  COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneNumber]                NVARCHAR (50)  COLLATE Latin1_General_CI_AS NULL,
    [IsSecondInsured]                BIT            DEFAULT ((0)) NULL,
    [CountryId]                      BIGINT         NULL,
    [CountryIdValue]                 NVARCHAR (50)  NULL,
    [IsActive]                       BIT            DEFAULT ((1)) NULL,
    [CreatedDate]                    DATETIME       DEFAULT (getutcdate()) NULL,
    [ModifiedDate]                   DATETIME       NULL,
    [CreatedBy]                      INT            NULL,
    [CreatedByValue]                 NVARCHAR (50)  NULL,
    [ModifiedBy]                     INT            NULL,
    [ModifiedByValue]                NVARCHAR (50)  NULL,
    [InceptTransactionId]            BIGINT         NULL,
    [MiddleName]                     NVARCHAR (100) NULL,
    [DriversLicenceNo]               NVARCHAR (100) NULL,
    [DriversLicenceIssueDate]        DATE           NULL,
    [DriversLicenceExpiryDate]       DATE           NULL,
    [DriversLicenceIssuePlace]       NVARCHAR (200) NULL,
    [Nationality]                    BIGINT         NULL,
    [NationalityValue]               NVARCHAR (50)  NULL,
    [DateofBirth]                    DATE           NULL,
    [PassportNo]                     NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [PassportIssueDate]              DATE           NULL,
    [PassportExpiryDate]             DATE           NULL,
    [VisaNo]                         NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [VisaIssueDate]                  DATE           NULL,
    [VisaExpiryDate]                 DATE           NULL,
    [EmiratesIdNo]                   NVARCHAR (200) COLLATE Latin1_General_BIN2 NULL,
    [EmiratesIdIssueDate]            DATE           NULL,
    [EmiratesIdExpiryDate]           DATE           NULL,
    [EmiratesIdIssuePlace]           NVARCHAR (200) NULL,
    [PhyAddBuildingName]             NVARCHAR (200) NULL,
    [PhyAddArea]                     NVARCHAR (100) NULL,
    [PhyAddEmirate]                  BIGINT         NULL,
    [PhyAddEmirateValue]             NVARCHAR (50)  NULL,
    [PhyAddCountryId]                BIGINT         NULL,
    [PhyAddCountryValue]             NVARCHAR (50)  NULL,
    [PostAddPOBoxNo]                 NVARCHAR (200) NULL,
    [PostAddEmirate]                 BIGINT         NULL,
    [PostAddEmirateValue]            NVARCHAR (50)  NULL,
    [PostAddCountryId]               BIGINT         NULL,
    [PostAddCountryValue]            NVARCHAR (50)  NULL,
    [ResidentialStatus]              BIGINT         NULL,
    [ResidentialStatusValue]         NVARCHAR (50)  NULL,
    [QualificationLevelId]           BIGINT         NULL,
    [QualificationLevelValue]        NVARCHAR (50)  NULL,
    [EmailAddress]                   NVARCHAR (100) COLLATE Latin1_General_CI_AS NULL,
    [IsContract]                     BIT            NULL,
    [IsSurety]                       BIT            NULL,
    [IsThirdPartyRegistration]       BIT            NULL,
    [JoiningDate]                    DATE           NULL,
    [MakaniNumber]                   NVARCHAR (200) NULL,
    [TradeLicenseNumber]             NVARCHAR (200) NULL,
    [TradelicenseExpiryDate]         DATE           NULL,
    [DateofInception]                DATE           NULL,
    [EmploymentCategoryId]           BIGINT         NULL,
    [PhyAddNearestLandMark]          NVARCHAR (200) NULL,
    [FaxCode]                        NVARCHAR (10)  NULL,
    [FaxNumber]                      NVARCHAR (50)  NULL,
    [FamilyName]                     NVARCHAR (200) NULL,
    [AreaName]                       NVARCHAR (200) NULL,
    [VillaOrApartmentNumber]         NVARCHAR (50)  NULL,
    [AreaCodeId]                     BIGINT         NULL,
    [OfficeTelephonenumberExtension] NVARCHAR (10)  NULL,
    [CityId]                         BIGINT         NULL,
    CONSTRAINT [InceptTransactionContact_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [InceptTransactionContact_FK_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id]),
    CONSTRAINT [InceptTransactionContact_FK_StaticValueAreaCodeId] FOREIGN KEY ([AreaCodeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [InceptTransactionContact_FK_StaticValueCityId] FOREIGN KEY ([CityId]) REFERENCES [dbo].[StaticValue] ([Id])
);

