CREATE TABLE [dbo].[InceptTransactionClient] (
    [Id]                             BIGINT          IDENTITY (1, 1) NOT NULL,
    [FirstName]                      NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [MiddleName]                     NVARCHAR (100)  NULL,
    [LastName]                       NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [Initials]                       NVARCHAR (50)   NULL,
    [DateofBirth]                    DATE            NULL,
    [PlaceOfBirth]                   NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [Nationality]                    BIGINT          NULL,
    [NoofDependents]                 INT             NULL,
    [MarriageDate]                   DATE            NULL,
    [MothersMaidenName]              NVARCHAR (200)  NULL,
    [UAEResidentSince]               DATE            NULL,
    [IDNumber]                       NVARCHAR (100)  NULL,
    [PassportNo]                     NVARCHAR (100)  NULL,
    [PassportIssueDate]              DATE            NULL,
    [PassportExpiryDate]             DATE            NULL,
    [PassportIssuePlace]             NVARCHAR (200)  NULL,
    [VisaNo]                         NVARCHAR (100)  NULL,
    [VisaIssueDate]                  DATE            NULL,
    [VisaExpiryDate]                 DATE            NULL,
    [VisaIssuePlace]                 NVARCHAR (200)  NULL,
    [EmiratesIdNo]                   NVARCHAR (200)  NULL,
    [EmiratesIdIssueDate]            DATE            NULL,
    [EmiratesIdExpiryDate]           DATE            NULL,
    [EmiratesIdIssuePlace]           NVARCHAR (200)  NULL,
    [DriversLicenceNo]               NVARCHAR (100)  NULL,
    [DriversLicenceIssueDate]        DATE            NULL,
    [DriversLicenceExpiryDate]       DATE            NULL,
    [DriversLicenceIssuePlace]       NVARCHAR (200)  NULL,
    [UAEDrivingLicenceNo]            NVARCHAR (100)  NULL,
    [PreferredName]                  NVARCHAR (100)  NULL,
    [Mobile]                         NVARCHAR (100)  NULL,
    [AlternativeMobile]              NVARCHAR (100)  NULL,
    [HomePhoneCode]                  NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [HomePhoneNumber]                NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneCode]                  NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneNumber]                NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [FaxCode]                        NVARCHAR (10)   NULL,
    [FaxNumber]                      NVARCHAR (50)   NULL,
    [ContactNumberInHomeCountry]     NVARCHAR (50)   NULL,
    [EmailAddress]                   NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [IsSMSAlertRequired]             BIT             CONSTRAINT [DF_InceptTransactionClient_IsSMSAlertRequired] DEFAULT ((0)) NULL,
    [PreferedMailingAddress]         INT             NULL,
    [NumberForSMSAlert]              NVARCHAR (100)  NULL,
    [PhyAddBuildingName]             NVARCHAR (200)  NULL,
    [PhyAddFlatNo]                   NVARCHAR (50)   NULL,
    [PhyAddUnitNo]                   NVARCHAR (50)   NULL,
    [PhyAddNearestLandmark]          NVARCHAR (200)  NULL,
    [PhyAddArea]                     NVARCHAR (100)  NULL,
    [PhyAddStreetName]               NVARCHAR (200)  NULL,
    [PostAddPOBoxNo]                 NVARCHAR (200)  NULL,
    [PhyAddEmirate]                  BIGINT          NULL,
    [PhyAddCity]                     NVARCHAR (200)  NULL,
    [PhyAddState]                    NVARCHAR (100)  NULL,
    [PhyAddZipCode]                  NVARCHAR (50)   NULL,
    [PostAddEmirate]                 BIGINT          NULL,
    [ResidentialStatus]              BIGINT          NULL,
    [NoOfYearsAtPesentAddress]       NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [RentPerMonth]                   DECIMAL (18, 2) NULL,
    [AddressInHomeCountry]           NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [CustomerType]                   INT             NULL,
    [NameOfKin]                      NVARCHAR (100)  NULL,
    [AddressOfKin]                   NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [ContactOfKin]                   NVARCHAR (50)   NULL,
    [CountryId]                      BIGINT          NULL,
    [IsActive]                       BIT             CONSTRAINT [InceptTransactionClient_DF_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]                    DATETIME        CONSTRAINT [InceptTransactionClient_DF_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                   DATETIME        NULL,
    [CreatedBy]                      INT             NOT NULL,
    [ModifiedBy]                     INT             NULL,
    [TitleId]                        BIGINT          NULL,
    [TitleValue]                     NVARCHAR (50)   NULL,
    [MaritalStatusId]                BIGINT          NULL,
    [MaritalStatusValue]             NVARCHAR (50)   NULL,
    [GenderId]                       BIGINT          NULL,
    [GenderValue]                    NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [IDTypeId]                       BIGINT          NULL,
    [IDTypeValue]                    NVARCHAR (50)   NULL,
    [PhyAddCountryId]                BIGINT          NULL,
    [PhyAddCountryValue]             NVARCHAR (50)   NULL,
    [PostAddCountryId]               BIGINT          NULL,
    [PostAddCountryValue]            NVARCHAR (50)   NULL,
    [HomeCountryId]                  BIGINT          NULL,
    [HomeCountryValue]               NVARCHAR (50)   NULL,
    [BankingDetailsId]               BIGINT          NULL,
    [CustomerTypeValue]              NVARCHAR (50)   NULL,
    [CountryValue]                   NVARCHAR (50)   NULL,
    [CreatedByValue]                 NVARCHAR (50)   NULL,
    [ModifiedByValue]                NVARCHAR (50)   NULL,
    [InceptTransactionId]            BIGINT          NOT NULL,
    [TransactionId]                  BIGINT          NOT NULL,
    [IsGuarantorApplication]         BIT             NULL,
    [RegularDriver]                  BIT             NULL,
    [ConditionsResidentPermit]       NVARCHAR (100)  NULL,
    [LanguageId]                     BIGINT          NULL,
    [LanguageValue]                  NVARCHAR (50)   NULL,
    [MarrageTypeId]                  BIGINT          NULL,
    [MarrageTypeValue]               NVARCHAR (50)   NULL,
    [SpousesName]                    NVARCHAR (100)  NULL,
    [SpousesBirthDate]               DATE            NULL,
    [PhyAddSurburb]                  NVARCHAR (50)   NULL,
    [PhyAddTown]                     NVARCHAR (50)   NULL,
    [PostAddSurburb]                 NVARCHAR (50)   NULL,
    [PostAddTown]                    NVARCHAR (50)   NULL,
    [SpecifyResidentialStatus]       NVARCHAR (100)  NULL,
    [PreviousHomeAddress]            NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PreferredCallTime]              BIGINT          NULL,
    [PreferredCallTimeValue]         NVARCHAR (50)   NULL,
    [NationalityValue]               NVARCHAR (50)   NULL,
    [ResidentialStatusValue]         NVARCHAR (50)   NULL,
    [CompanyName]                    NVARCHAR (MAX)  NULL,
    [ComNatureOfBusiness]            BIGINT          NULL,
    [ComNatureOfBusinessValue]       NVARCHAR (50)   NULL,
    [CompanyStartDate]               DATE            NULL,
    [ComTradeLicenceStartDate]       DATE            NULL,
    [ComTradeLicenceExpiryDate]      DATE            NULL,
    [ComVATNumber]                   NVARCHAR (50)   NULL,
    [ComPhyAddBuildingName]          NVARCHAR (200)  NULL,
    [ComPhyAddStreetName]            NVARCHAR (100)  NULL,
    [ComPhyAddEmirate]               BIGINT          NULL,
    [ComPhyAddPostCode]              NVARCHAR (100)  NULL,
    [ComPhyAddCountryId]             BIGINT          NULL,
    [ComPhyAddCountryValue]          NVARCHAR (50)   NULL,
    [ComTradingAs]                   NVARCHAR (50)   NULL,
    [ComRegistrationNumber]          NVARCHAR (50)   NULL,
    [ComNoOfYearsInBusiness]         INT             NULL,
    [ComLandlord]                    NVARCHAR (100)  NULL,
    [ComHoldingCompany]              NVARCHAR (100)  NULL,
    [ComAssociatedCompany]           NVARCHAR (200)  NULL,
    [ComSubsidaryCompany]            NVARCHAR (200)  NULL,
    [ComCompanyRepresentative]       NVARCHAR (100)  NULL,
    [ComFloorNo]                     INT             NULL,
    [ComYearsAtCurrentAddress]       INT             NULL,
    [ComEmirate]                     BIGINT          NULL,
    [PhyAdd1]                        NVARCHAR (200)  NULL,
    [PhyAdd2]                        NVARCHAR (200)  NULL,
    [PhyAdd3]                        NVARCHAR (200)  NULL,
    [PostAdd1]                       NVARCHAR (200)  NULL,
    [PostAdd2]                       NVARCHAR (200)  NULL,
    [PostAdd3]                       NVARCHAR (200)  NULL,
    [FinanceStatus]                  BIGINT          NULL,
    [FinanceStatusValue]             NVARCHAR (50)   NULL,
    [FinanceStatusNotes]             NVARCHAR (500)  NULL,
    [ConditionsOfResidentsPermit]    NVARCHAR (500)  NULL,
    [BusinessTypeId]                 BIGINT          NULL,
    [BusinessTypeValue]              NVARCHAR (50)   NULL,
    [QualificationId]                BIGINT          NULL,
    [QualificationValue]             NVARCHAR (50)   NULL,
    [PhyAddEmirateValue]             NVARCHAR (50)   NULL,
    [PostAddEmirateValue]            NVARCHAR (100)  NULL,
    [ComPhyAddEmirateValue]          NVARCHAR (100)  NULL,
    [ComEmirateValue]                NVARCHAR (50)   NULL,
    [PermitNumber]                   NVARCHAR (100)  NULL,
    [PermitIssueDate]                DATE            NULL,
    [PermitExpiryDate]               DATE            NULL,
    [IdIssueDate]                    DATE            NULL,
    [IdExpiryDate]                   DATE            NULL,
    [SpecifyMaritalStatus]           NVARCHAR (100)  NULL,
    [EthnicGroup]                    BIGINT          NULL,
    [EthnicGroupValue]               NVARCHAR (200)  NULL,
    [NoOfMonthsAtPesentAddress]      NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [MarketingSource]                BIGINT          NULL,
    [MarketingSourceValue]           NVARCHAR (200)  NULL,
    [ClaimFreeGroup]                 BIGINT          NULL,
    [ClaimFreeGroupValue]            NVARCHAR (50)   NULL,
    [IsCompanyVATRegistered]         BIT             NULL,
    [PhyAdd4]                        NVARCHAR (200)  NULL,
    [PhyAddCode]                     NVARCHAR (100)  NULL,
    [PostAdd4]                       NVARCHAR (200)  NULL,
    [PostAddCode]                    NVARCHAR (100)  NULL,
    [IsCompanyBlackOwned]            BIT             NULL,
    [IsCompanyBalanceSheet]          BIT             NULL,
    [CompanyFinancialYear]           NVARCHAR (200)  NULL,
    [CompanyTurnover]                DECIMAL (18, 4) NULL,
    [CompanyTotalAssets]             DECIMAL (18, 4) NULL,
    [ComPhyAdd1]                     NVARCHAR (200)  NULL,
    [ComPhyAdd2]                     NVARCHAR (200)  NULL,
    [ComPhyAdd3]                     NVARCHAR (200)  NULL,
    [ComPhyAdd4]                     NVARCHAR (200)  NULL,
    [ComPhyAddCode]                  NVARCHAR (100)  NULL,
    [HomeCountryAddress1]            NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [HomeCountryAddress2]            NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [HomeCountryAddress3]            NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [HomeCountryAddress4]            NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [HomeCountryAddressCode]         NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PreferredLanguage]              NVARCHAR (200)  NULL,
    [TradeLicenseNumber]             NVARCHAR (200)  NULL,
    [IsSpouseDetailsIncluded]        BIT             DEFAULT ((0)) NULL,
    [ComPhyAddMakaniNumber]          NVARCHAR (200)  NULL,
    [OfficeBuildingName]             NVARCHAR (200)  NULL,
    [OfficeStreetName]               NVARCHAR (200)  NULL,
    [OfficeEmirate]                  BIGINT          NULL,
    [OfficeCountry]                  BIGINT          NULL,
    [OfficeNearestLandmark]          NVARCHAR (200)  NULL,
    [OfficeMakaniNumber]             NVARCHAR (200)  NULL,
    [ComNumberofFleetVehicles]       BIGINT          NULL,
    [ComNumberofMortgagedVehicles]   BIGINT          NULL,
    [FamilyName]                     NVARCHAR (200)  NULL,
    [FirstNameInArabic]              NVARCHAR (200)  NULL,
    [MiddleNameInArabic]             NVARCHAR (200)  NULL,
    [LastNameInArabic]               NVARCHAR (200)  NULL,
    [FamilyNameInArabic]             NVARCHAR (200)  NULL,
    [IsResident]                     BIT             NULL,
    [ComNoOfPeopleEmployed]          INT             NULL,
    [ComTradeLicensePlaceofIssue]    NVARCHAR (200)  NULL,
    [AreaName]                       NVARCHAR (200)  NULL,
    [VillaOrApartmentNumber]         NVARCHAR (50)   NULL,
    [AreaCodeId]                     BIGINT          NULL,
    [OfficeTelephonenumberExtension] NVARCHAR (10)   NULL,
    [CityId]                         BIGINT          NULL,
    [NewInCountry]                   BIT             NULL,
    CONSTRAINT [InceptTransactionClient_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InceptTransactionClient_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id]),
    CONSTRAINT [InceptTransactionClient_FK_StaticValueAreaCodeId] FOREIGN KEY ([AreaCodeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [InceptTransactionClient_FK_StaticValueCityId] FOREIGN KEY ([CityId]) REFERENCES [dbo].[StaticValue] ([Id])
);

