CREATE TABLE [dbo].[InceptTransactionFinanceApplication] (
    [Id]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    [TransactionId]        BIGINT          NOT NULL,
    [ClientId]             BIGINT          NULL,
    [CompanyId]            BIGINT          NULL,
    [CompanyValue]         NVARCHAR (MAX)  NULL,
    [Response]             NVARCHAR (4000) NULL,
    [CreatedDate]          DATETIME        NULL,
    [ModifiedDate]         DATETIME        NULL,
    [CreatedBy]            INT             NULL,
    [CreatedByValue]       NVARCHAR (50)   NULL,
    [ModifiedBy]           INT             NULL,
    [ModifiedByValue]      NVARCHAR (50)   NULL,
    [InceptTransactionId]  BIGINT          NOT NULL,
    [CountryId]            BIGINT          NULL,
    [CountryValue]         NVARCHAR (50)   NULL,
    [IsActive]             BIT             CONSTRAINT [DF__InceptTra__IsAct__02CA9745] DEFAULT ((1)) NULL,
    [CompanyCompanyTypeId] BIGINT          NULL,
    [FinanceStatusId]      BIGINT          NULL,
    [FinanceStatusValue]   NVARCHAR (50)   NULL,
    [FinanceStatusNotes]   NVARCHAR (4000) NULL,
    [LeadNumber]           BIGINT          NULL,
    [FinanceAccountNumber] NVARCHAR (100)  NULL,
    [LOIIssueDate]         DATETIME        NULL,
    [LOIExpiryDate]        DATETIME        NULL,
    [LocalPurchaseNumber]  NVARCHAR (200)  NULL,
    [LOPIssueDate]         DATETIME        NULL,
    [LOPExpiryDate]        DATETIME        NULL,
    CONSTRAINT [PK_InceptTransactionFinanceApplication] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InceptTransactionFinanceApplication_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id])
);

