CREATE TABLE [dbo].[InceptTransactionVehicle] (
    [Id]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [Model]                 NVARCHAR (100)  NULL,
    [IntroductionDate]      DATE            NULL,
    [EngineCapacity]        INT             NULL,
    [EnginePower]           NVARCHAR (100)  NULL,
    [Cylinders]             INT             NULL,
    [Doors]                 NVARCHAR (50)   NULL,
    [CountryId]             BIGINT          NULL,
    [IsActive]              BIT             NOT NULL,
    [CreatedDate]           DATETIME        NOT NULL,
    [ModifiedDate]          DATETIME        NULL,
    [CreatedBy]             INT             NOT NULL,
    [ModifiedBy]            INT             NULL,
    [TransactionId]         BIGINT          NOT NULL,
    [VehicleCode]           NVARCHAR (100)  NULL,
    [ManufacturerId]        BIGINT          NULL,
    [ManufacturerValue]     NVARCHAR (50)   NULL,
    [VehicleTypeId]         BIGINT          NULL,
    [VehicleTypeValue]      NVARCHAR (50)   NULL,
    [BodyTypeId]            BIGINT          NULL,
    [BodyTypeValue]         NVARCHAR (50)   NULL,
    [TerminationDate]       DATE            NULL,
    [Weight]                DECIMAL (18, 2) NULL,
    [CountryValue]          NVARCHAR (50)   NULL,
    [CreatedByValue]        NVARCHAR (50)   NULL,
    [ModifiedByValue]       NVARCHAR (50)   NULL,
    [InceptTransactionId]   BIGINT          NOT NULL,
    [GroupId]               BIGINT          NULL,
    [GroupValue]            NVARCHAR (100)  NULL,
    [BranchId]              BIGINT          NULL,
    [BranchValue]           NVARCHAR (100)  NULL,
    [ModelYear]             INT             NULL,
    [TransmissionTypeId]    BIGINT          NULL,
    [TransmissionTypeValue] NVARCHAR (100)  NULL,
    [Trim]                  NVARCHAR (50)   NULL,
    [DownPaymentMadeTo]     BIGINT          NULL,
    [AgencyBranchId]        BIGINT          NULL,
    [AgencyLocation]        NVARCHAR (200)  NULL,
    [TrafficFileNo]         NVARCHAR (100)  NULL,
    [RegistrationTypeId]    BIGINT          NULL,
    [RegistrationName]      NVARCHAR (200)  NULL,
    [ThirdPartyRelationId]  BIGINT          NULL,
    [ModeOfDownPayment]     BIGINT          NULL,
    [SUKUKAmount]           DECIMAL (18, 2) NULL,
    [SUKUKTenure]           INT             NULL,
    [FeesCollection]        BIGINT          NULL,
    CONSTRAINT [InceptTransactionVehicle_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InceptTransactionVehicle_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id]),
    CONSTRAINT [InceptTransactionVehicle_FK_StaticValueAgencyBranchId] FOREIGN KEY ([AgencyBranchId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [InceptTransactionVehicle_FK_StaticValueFeesCollection] FOREIGN KEY ([FeesCollection]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [InceptTransactionVehicle_FK_StaticValueModeOfDownPayment] FOREIGN KEY ([ModeOfDownPayment]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [InceptTransactionVehicle_FK_StaticValueRegistrationTypeId] FOREIGN KEY ([RegistrationTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [InceptTransactionVehicle_FK_StaticValueThirdPartyRelationId] FOREIGN KEY ([ThirdPartyRelationId]) REFERENCES [dbo].[StaticValue] ([Id])
);

