CREATE TABLE [dbo].[InceptTransactionProduct] (
    [Id]                        BIGINT          IDENTITY (1, 1) NOT NULL,
    [RetailPrice]               DECIMAL (18, 2) NULL,
    [IsPayByCash]               BIT             CONSTRAINT [InceptTransactionProduct_DF_PayByCash] DEFAULT ((0)) NOT NULL,
    [CountryId]                 BIGINT          NULL,
    [IsActive]                  BIT             CONSTRAINT [InceptTransactionProduct_DF_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]               DATETIME        CONSTRAINT [InceptTransactionProduct_DF_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]              DATETIME        NULL,
    [CreatedBy]                 INT             NOT NULL,
    [ModifiedBy]                INT             NULL,
    [TransactionId]             BIGINT          NOT NULL,
    [ProductTypeId]             BIGINT          NULL,
    [ProductTypeValue]          NVARCHAR (100)  NULL,
    [ProductSubTypeId]          BIGINT          NULL,
    [ProductSubTypeValue]       NVARCHAR (100)  NULL,
    [ProductId]                 BIGINT          NULL,
    [ProductValue]              NVARCHAR (100)  NULL,
    [ProductOptionId]           BIGINT          NULL,
    [ProductOptionValue]        NVARCHAR (100)  NULL,
    [ProductLineId]             BIGINT          NULL,
    [NotOffered]                BIT             NULL,
    [Decline]                   BIT             NULL,
    [NotApplicable]             BIT             NULL,
    [AdditionalKM]              INT             NULL,
    [AdditionalMonth]           INT             NULL,
    [ExpiryKM]                  INT             NULL,
    [ExpiryMonth]               INT             NULL,
    [IsInsuranceProduct]        BIT             NULL,
    [BodyConditionId]           BIGINT          NULL,
    [BodyConditionValue]        NVARCHAR (50)   NULL,
    [MechanicalConditionId]     BIGINT          NULL,
    [MechanicalConditionValue]  NVARCHAR (50)   NULL,
    [CountryValue]              NVARCHAR (50)   NULL,
    [CreatedByValue]            NVARCHAR (50)   NULL,
    [ModifiedByValue]           NVARCHAR (50)   NULL,
    [InceptTransactionId]       BIGINT          NOT NULL,
    [IsEditablePayover]         BIT             NULL,
    [TransactionTypeId]         BIGINT          NULL,
    [Payover]                   DECIMAL (18, 2) NULL,
    [InsuranceFrom]             DATE            NULL,
    [InsuranceTo]               DATE            NULL,
    [CalculationTemplateAmount] DECIMAL (18, 4) NULL,
    CONSTRAINT [InceptTransactionProduct_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InceptTransactionProduct_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This table stores the incepted transaction Product information.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'InceptTransactionProduct';

