CREATE TABLE [dbo].[InceptTransactionBankingDetails] (
    [Id]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [BranchName]                  NVARCHAR (200)  NULL,
    [AccountType]                 BIGINT          NULL,
    [AccountNo]                   NVARCHAR (200)  NULL,
    [LoanType]                    BIGINT          NULL,
    [IsSalaryTransferedToBank]    BIT             NULL,
    [LoanOutstanding]             DECIMAL (18, 2) NULL,
    [Emirate]                     NVARCHAR (200)  NULL,
    [NoOfYearsAccountHeld]        INT             NULL,
    [CountryId]                   BIGINT          NULL,
    [IsActive]                    BIT             CONSTRAINT [DF__InceptTransacti__IsAct__3871AF88] DEFAULT ((1)) NOT NULL,
    [CreatedBy]                   INT             NOT NULL,
    [ModifiedBy]                  INT             NULL,
    [CreatedDate]                 DATETIME        CONSTRAINT [DF__InceptTransacti__Creat__3965D3C1] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                DATETIME        NULL,
    [BankId]                      BIGINT          NULL,
    [BankValue]                   NVARCHAR (100)  NULL,
    [AccountTypeValue]            NVARCHAR (50)   NULL,
    [LoanTypeValue]               NVARCHAR (50)   NULL,
    [CountryValue]                NVARCHAR (50)   NULL,
    [CreatedByValue]              NVARCHAR (50)   NULL,
    [ModifiedByValue]             NVARCHAR (50)   NULL,
    [InceptTransactionId]         BIGINT          NOT NULL,
    [TransactionId]               BIGINT          NOT NULL,
    [BranchCode]                  NVARCHAR (50)   NULL,
    [BranchType]                  NVARCHAR (50)   NULL,
    [NameOfAccountHolder]         NVARCHAR (100)  NULL,
    [DateOfAccountOpened]         DATE            NULL,
    [MonthlyInstalment]           DECIMAL (18, 2) NULL,
    [CreditCardTypeId]            BIGINT          NULL,
    [CreditCardTypeValue]         NVARCHAR (50)   NULL,
    [CreditCardNumber]            NVARCHAR (50)   NULL,
    [CreditCardDateofIssue]       DATE            NULL,
    [CreditCardDateofExpiry]      DATE            NULL,
    [AccountDetailsType]          INT             NULL,
    [IsIncludeDetails]            BIT             DEFAULT ((0)) NULL,
    [DebitOrderDate]              DATE            NULL,
    [IsSendDebitOrderDetails]     BIT             NULL,
    [DebitOrderStartDate]         DATE            NULL,
    [DebitOrderEndDate]           DATE            NULL,
    [NoOfPaymentPeriods]          INT             NULL,
    [DebitAmount]                 DECIMAL (18, 8) NULL,
    [MaximumAmount]               DECIMAL (18, 8) NULL,
    [DebitOrderCompanyID]         BIGINT          NULL,
    [IsDebitOrder]                BIT             NULL,
    [CreditCardOutStanding]       DECIMAL (18, 8) NULL,
    [FirstEMIDate]                DATE            NULL,
    [PaymentMethod]               BIGINT          NULL,
    [IBANNumber]                  NVARCHAR (200)  NULL,
    [NoOfEMIsForObligation]       INT             NULL,
    [RepaymentAccount]            BIT             NULL,
    [IsExistingCASAAccountNumber] BIT             NULL,
    [ExistingCASAAccountNumber]   NVARCHAR (200)  NULL,
    [IsDownPaymentAccount]        BIT             NULL,
    [BranchId]                    BIGINT          NULL,
    [IsFeeCollectionbyDebitOrder] BIT             NULL,
    CONSTRAINT [InceptClientBankingDetails_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InceptTransactionBankingDetails_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id]),
    CONSTRAINT [InceptTransactionBankingDetails_FK_StaticValueBranchId] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[StaticValue] ([Id])
);

