CREATE TABLE [dbo].[InceptTransaction] (
    [Id]                                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [TransactionId]                           BIGINT          NOT NULL,
    [IsDealSighted]                           BIT             CONSTRAINT [InceptTransaction_DF_IsDealSighted] DEFAULT ((0)) NOT NULL,
    [SalesReferenceNumber]                    NVARCHAR (100)  NULL,
    [CompanyType]                             BIGINT          NULL,
    [IsCashTransaction]                       BIT             CONSTRAINT [InceptTransaction_DF_CashTransaction] DEFAULT ((0)) NOT NULL,
    [PreferredInterestRate]                   DECIMAL (18, 2) NULL,
    [FinanceDealScheme]                       BIT             NULL,
    [IsPreArrangedFinance]                    BIT             CONSTRAINT [InceptTransaction_DF_PreArrangedFinance] DEFAULT ((0)) NOT NULL,
    [FinanceAccountNumber]                    NVARCHAR (100)  NULL,
    [RetailPrice]                             DECIMAL (18, 2) NULL,
    [Discount]                                DECIMAL (18, 2) NULL,
    [DocInvoiceNo]                            NVARCHAR (50)   NULL,
    [StockNo]                                 NVARCHAR (50)   NULL,
    [IsShareDetailsWithinCompany]             BIT             CONSTRAINT [DF_InceptTransaction_IsShareDetailsWithinCompany] DEFAULT ((0)) NULL,
    [IsShareDetailsAmongPartner]              BIT             CONSTRAINT [DF_InceptTransaction_IsShareDetailsAmongPartner] DEFAULT ((0)) NULL,
    [IsReceiveMarketingInfo]                  BIT             CONSTRAINT [DF_InceptTransaction_IsReceiveMarketingInfo] DEFAULT ((0)) NULL,
    [TransactionSchedulePath]                 NVARCHAR (500)  NULL,
    [CountryId]                               BIGINT          NULL,
    [IsActive]                                BIT             CONSTRAINT [InceptTransaction_DF_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]                             DATETIME        CONSTRAINT [InceptTransaction_DF_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                            DATETIME        NULL,
    [InceptedBy]                              INT             NULL,
    [CreatedBy]                               INT             NULL,
    [ModifiedBy]                              INT             NULL,
    [IsTransactionIncepted]                   BIT             CONSTRAINT [DF__InceptTra__IsTra__19E306C7] DEFAULT ((0)) NULL,
    [GroupId]                                 BIGINT          NULL,
    [GroupValue]                              NVARCHAR (100)  NULL,
    [BranchId]                                BIGINT          NULL,
    [BranchValue]                             NVARCHAR (100)  NULL,
    [TransactionTypeId]                       BIGINT          NULL,
    [TransactionTypeValue]                    NVARCHAR (200)  NULL,
    [TransactionStatusId]                     BIGINT          NULL,
    [TransactionStatusValue]                  NVARCHAR (200)  NULL,
    [TransactionStatusNotes]                  NVARCHAR (4000) NULL,
    [FinanceStatusId]                         BIGINT          NULL,
    [FinanceStatusValue]                      NVARCHAR (100)  NULL,
    [FinanceStatusNotes]                      NVARCHAR (4000) NULL,
    [SalesCompanyId]                          BIGINT          NULL,
    [SalesCompanyValue]                       NVARCHAR (MAX)  NULL,
    [SalesPersonId]                           BIGINT          NULL,
    [SalesPersonValue]                        NVARCHAR (100)  NULL,
    [BusinessManagerId]                       BIGINT          NULL,
    [BusinessManagerValue]                    NVARCHAR (100)  NULL,
    [CompanyTypeValue]                        NVARCHAR (100)  NULL,
    [FinanceCompanyId]                        BIGINT          NULL,
    [FinanceCompanyValue]                     NVARCHAR (MAX)  NULL,
    [PaymentType]                             NVARCHAR (50)   NULL,
    [FinanceTermId]                           BIGINT          NULL,
    [FinanceTermValue]                        INT             NULL,
    [VehicleId]                               BIGINT          NULL,
    [VehicleUse]                              BIGINT          NULL,
    [VehicleUseValue]                         NVARCHAR (200)  NULL,
    [VehicleCondition]                        BIGINT          NULL,
    [VehicleConditionValue]                   NVARCHAR (100)  NULL,
    [VehicleRegistrationName]                 NVARCHAR (100)  NULL,
    [VehicleRegisteredAt]                     NVARCHAR (100)  NULL,
    [ValuationDate]                           DATE            NULL,
    [Valuator]                                NVARCHAR (100)  NULL,
    [DisburseId]                              BIGINT          NULL,
    [DisburseValue]                           NVARCHAR (200)  NULL,
    [PrivateKey]                              NVARCHAR (100)  NULL,
    [IsAssetInsured]                          BIT             NULL,
    [TotalDeposit]                            DECIMAL (18, 2) NULL,
    [BalloonValue]                            DECIMAL (18, 2) NULL,
    [BalloonPercentage]                       DECIMAL (18, 2) NULL,
    [IsTradeIn]                               BIT             DEFAULT ((0)) NULL,
    [IsTradeInCashTransaction]                BIT             DEFAULT ((0)) NULL,
    [TradeInFinanceCompanyValue]              NVARCHAR (MAX)  NULL,
    [TradeInFinanceCompanyId]                 BIGINT          NULL,
    [TradeInCarFinanceAccNumber]              NVARCHAR (100)  NULL,
    [TradeInCurrentInstalment]                DECIMAL (18, 2) NULL,
    [TradeInValue]                            DECIMAL (18, 2) NULL,
    [TradeInSettlementValue]                  DECIMAL (18, 2) NULL,
    [TradeInCashPayback]                      DECIMAL (18, 2) NULL,
    [NetTradeInDepositValue]                  DECIMAL (18, 2) NULL,
    [TransactionClientId]                     BIGINT          NULL,
    [TransactionDriverId]                     BIGINT          NULL,
    [ChassisNumber]                           NVARCHAR (100)  NULL,
    [EngineNumber]                            NVARCHAR (100)  NULL,
    [RegistrationNumber]                      NVARCHAR (100)  NULL,
    [FirstRegistrationDate]                   DATETIME        NULL,
    [Color]                                   NVARCHAR (50)   NULL,
    [VehicleEmirate]                          BIGINT          NULL,
    [DownPayment]                             DECIMAL (18, 2) NULL,
    [InterestRateTypeId]                      BIGINT          NULL,
    [InterestRateTypeValue]                   NVARCHAR (50)   NULL,
    [CountryValue]                            NVARCHAR (50)   NULL,
    [InceptedByValue]                         NVARCHAR (50)   NULL,
    [CreatedByValue]                          NVARCHAR (50)   NULL,
    [ModifiedByValue]                         NVARCHAR (50)   NULL,
    [IsIncepted]                              BIT             DEFAULT ((0)) NULL,
    [InceptDate]                              DATETIME        NULL,
    [LocalPurchaseNumber]                     NVARCHAR (100)  NULL,
    [TotalSumInsured]                         DECIMAL (18, 2) NULL,
    [ReferenceNumber]                         NVARCHAR (50)   NULL,
    [VehileDescription]                       NVARCHAR (200)  NULL,
    [OdometerReading]                         INT             NULL,
    [FinanceType]                             BIGINT          NULL,
    [FinanceTypeValue]                        NVARCHAR (50)   NULL,
    [SellingPrice]                            DECIMAL (18, 2) NULL,
    [VehicleCostPrice]                        DECIMAL (18, 2) NULL,
    [Immoblizer]                              BIGINT          NULL,
    [ImmoblizerValue]                         NVARCHAR (50)   NULL,
    [IsManufacturerWarranty]                  BIT             NULL,
    [ManWarrantyExpiryMonths]                 BIGINT          NULL,
    [ManWarrantyExpiryKM]                     INT             NULL,
    [ExistingWarranty]                        BIT             NULL,
    [ExistingWarrantyExpiryDate]              DATE            NULL,
    [ExistingWarrantyExpiryKM]                INT             NULL,
    [ManufacturePlanType]                     BIGINT          NULL,
    [ManufacturePlanTypeValue]                NVARCHAR (50)   NULL,
    [ManPlanExpiryMonths]                     INT             NULL,
    [ManPlanExpiryKM]                         INT             NULL,
    [ExistingPlanType]                        BIGINT          NULL,
    [ExistingPlanTypeValue]                   NVARCHAR (50)   NULL,
    [ExistingPlanExpiryDate]                  DATE            NULL,
    [ExistingPlanExpiryKM]                    INT             NULL,
    [PaymentTypeValue]                        NVARCHAR (50)   NULL,
    [ProfitRate]                              DECIMAL (18, 2) NULL,
    [PreferredCallTime]                       BIGINT          NULL,
    [PreferredCallTimeValue]                  NVARCHAR (50)   NULL,
    [VehicleTradeInValue]                     DECIMAL (18, 2) NULL,
    [IsManufaturerApprovedUsedVehicle]        BIT             NULL,
    [IsFullServiceHistory]                    BIT             NULL,
    [Kilometers]                              INT             NULL,
    [VehicleEmirateValue]                     NVARCHAR (50)   NULL,
    [ManWarrantyExpiryMonthsValue]            INT             NULL,
    [VINNumber]                               NVARCHAR (50)   NULL,
    [UninceptReason]                          NVARCHAR (1000) NULL,
    [DocInvoiceDate]                          DATETIME        NULL,
    [DocInvoicePaidDate]                      DATETIME        NULL,
    [VehicleDeliveryDate]                     DATETIME        NULL,
    [OtherFee]                                DECIMAL (18, 2) NULL,
    [OtherCost]                               DECIMAL (18, 2) NULL,
    [DICAmount]                               DECIMAL (18, 2) NULL,
    [DICPercentage]                           DECIMAL (18, 2) NULL,
    [TransactionCreatedDate]                  DATETIME        NULL,
    [TransactionNo]                           BIGINT          NULL,
    [SalesPersonEmpNo]                        NVARCHAR (100)  NULL,
    [BusinessManagerEmpNo]                    NVARCHAR (100)  NULL,
    [StampDutyFees]                           DECIMAL (18, 2) NULL,
    [BankDocumentationFees]                   DECIMAL (18, 2) NULL,
    [PayOutRequestDate]                       DATETIME        NULL,
    [CallBackCustomerDateTime]                DATETIME        NULL,
    [IsDisclosureofPersonalInfo]              BIT             NULL,
    [IsDebitOrderInformationAndAuthorization] BIT             NULL,
    [IsCustomerBankStatement]                 BIT             NULL,
    [VehicleDescription]                      NVARCHAR (200)  NULL,
    [TransactionSource]                       NVARCHAR (100)  NULL,
    [UninceptDate]                            DATETIME        NULL,
    [UninceptBy]                              NVARCHAR (1000) NULL,
    [PrimeInterestRate]                       DECIMAL (18, 2) NULL,
    [FleetNumber]                             NVARCHAR (MAX)  NULL,
    [BusinessSegment]                         BIGINT          NULL,
    [ParentTransactionId]                     BIGINT          NULL,
    [TransactionFee]                          DECIMAL (18, 2) NULL,
    [LOIIssueDate]                            DATETIME        NULL,
    [LOIExpiryDate]                           DATETIME        NULL,
    [LOPIssueDate]                            DATETIME        NULL,
    [LOPExpiryDate]                           DATETIME        NULL,
    [Scheme]                                  NVARCHAR (MAX)  NULL,
    CONSTRAINT [InceptTransaction_PK] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This Table stores the incepted transaction details', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'InceptTransaction';

