CREATE TABLE [dbo].[InceptTransactionEmployerDetails] (
    [Id]                                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [TransactionId]                       BIGINT         NOT NULL,
    [EmploymentTypeId]                    BIGINT         NULL,
    [EmploymentTypeValue]                 NVARCHAR (50)  NULL,
    [NameofEmployer]                      NVARCHAR (200) NULL,
    [JoiningDate]                         DATE           NULL,
    [EmployeeNumber]                      NVARCHAR (200) NULL,
    [Designation]                         NVARCHAR (200) NULL,
    [TypeOfOrganization]                  BIGINT         NULL,
    [Sector]                              NVARCHAR (200) NULL,
    [PreviousEmployer]                    NVARCHAR (200) NULL,
    [NoOfYearsWithPreviousEmployer]       INT            NULL,
    [BusinessName]                        NVARCHAR (200) COLLATE Latin1_General_CI_AS NULL,
    [DateofInception]                     DATE           NULL,
    [TradeLicenceNo]                      NVARCHAR (200) NULL,
    [TradeLicenceExpiryDate]              DATE           NULL,
    [CountryId]                           BIGINT         NULL,
    [CountryValue]                        NVARCHAR (50)  NULL,
    [CreatedDate]                         DATETIME       CONSTRAINT [DF__InceptTra__Creat__395BB220] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                        DATETIME       NULL,
    [CreatedBy]                           INT            NULL,
    [CreatedByValue]                      NVARCHAR (50)  NULL,
    [ModifiedBy]                          INT            NULL,
    [ModifiedByValue]                     NVARCHAR (50)  NULL,
    [InceptTransactionId]                 BIGINT         NULL,
    [IsActive]                            BIT            CONSTRAINT [DF__InceptTra__IsAct__01D6730C] DEFAULT ((1)) NULL,
    [TypeOfOrganizationValue]             NVARCHAR (50)  NULL,
    [SalaryCycle]                         BIGINT         NULL,
    [SalaryCycleValue]                    NVARCHAR (200) NULL,
    [PhyAdd1]                             NVARCHAR (200) NULL,
    [PhyAdd2]                             NVARCHAR (200) NULL,
    [PhyAdd3]                             NVARCHAR (200) NULL,
    [PhyAdd4]                             NVARCHAR (200) NULL,
    [Code]                                NVARCHAR (50)  NULL,
    [NatureOfBusiness]                    BIGINT         NULL,
    [MODRank]                             NVARCHAR (200) NULL,
    [PreviousEmployerAddress]             NVARCHAR (500) NULL,
    [PreviousEmployerTelephoneNumberCode] NVARCHAR (10)  NULL,
    [PreviousEmployerTelephoneNumber]     NVARCHAR (50)  NULL,
    [CurrentEmployerDateOfEstablishment]  DATE           NULL,
    [OccupationLevelId]                   BIGINT         NULL,
    [DesignationId]                       BIGINT         NULL,
    CONSTRAINT [InceptTransactionEmployerDetails_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [InceptTransactionEmployerDetails_FK_InceptTransaction] FOREIGN KEY ([InceptTransactionId]) REFERENCES [dbo].[InceptTransaction] ([Id])
);

