CREATE TABLE [dbo].[InsuranceLeadReportFilterMapping] (
    [Id]                          BIGINT   IDENTITY (1, 1) NOT NULL,
    [InsuranceLeadReportFilterId] BIGINT   NULL,
    [GroupId]                     BIGINT   NULL,
    [BranchId]                    BIGINT   NULL,
    [BusinessManagerId]           INT      NULL,
    [SalesPersonId]               BIGINT   NULL,
    [CompanyTypeId]               BIGINT   NULL,
    [CompanyId]                   BIGINT   NULL,
    [CriteriaEnum]                INT      NULL,
    [IsActive]                    BIT      CONSTRAINT [DF__Insurance__IsAct__299E4456] DEFAULT ((0)) NOT NULL,
    [CreatedDate]                 DATETIME NULL,
    [ModifiedDate]                DATETIME NULL,
    [CreatedBy]                   INT      NULL,
    [ModifiedBy]                  INT      NULL,
    [TransactionTypeId]           BIGINT   NULL,
    CONSTRAINT [PK_InsuranceLeadReportFilterMapping] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_Branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[Branch] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_CompanyCompanyTypeMapping] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_CompanyType] FOREIGN KEY ([CompanyTypeId]) REFERENCES [dbo].[CompanyType] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_InsuranceLeadReportFilter] FOREIGN KEY ([InsuranceLeadReportFilterId]) REFERENCES [dbo].[InsuranceLeadReportFilter] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_SalesPerson] FOREIGN KEY ([SalesPersonId]) REFERENCES [dbo].[SalesPerson] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_StaticValue] FOREIGN KEY ([TransactionTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_Users_BusinessManager] FOREIGN KEY ([BusinessManagerId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_Users_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_InsuranceLeadReportFilterMapping_Users_ModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

