CREATE TABLE [dbo].[PayoverReportFilter] (
    [Id]                      BIGINT         IDENTITY (1, 1) NOT NULL,
    [MasterReportId]          BIGINT         NOT NULL,
    [ProductTypeId]           BIGINT         NULL,
    [ProductSubTypeId]        BIGINT         NULL,
    [ProductId]               BIGINT         NULL,
    [StartDate]               DATE           NULL,
    [EndDate]                 DATE           NULL,
    [IsInceptDate]            BIT            DEFAULT ((0)) NOT NULL,
    [IsInvoiceDate]           BIT            DEFAULT ((0)) NOT NULL,
    [IsInvoicePaidDate]       BIT            DEFAULT ((0)) NOT NULL,
    [AdministratorId]         BIGINT         NULL,
    [ClaimId]                 BIGINT         NULL,
    [OwnerId]                 BIGINT         NULL,
    [UnderwriterId]           BIGINT         NULL,
    [CopiedFrom]              BIGINT         NULL,
    [IsEmailReport]           BIT            DEFAULT ((0)) NOT NULL,
    [Email]                   NVARCHAR (100) NULL,
    [CountryId]               BIGINT         NULL,
    [IsActive]                BIT            DEFAULT ((1)) NOT NULL,
    [CreatedDate]             DATETIME       DEFAULT (getutcdate()) NULL,
    [ModifiedDate]            DATETIME       NULL,
    [CreatedBy]               INT            NULL,
    [ModifiedBy]              INT            NULL,
    [IsIncludeMonthlyProduct] BIT            CONSTRAINT [DF_PayoverReportFilter_IsIncludeMonthlyProduct] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_PayoverReportFilter] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_PayoverReportFilter_CompanyCompanyTypeMapping] FOREIGN KEY ([AdministratorId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_CompanyCompanyTypeMapping1] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_CompanyCompanyTypeMapping2] FOREIGN KEY ([UnderwriterId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_CompanyCompanyTypeMapping3] FOREIGN KEY ([ClaimId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_MasterReport] FOREIGN KEY ([MasterReportId]) REFERENCES [dbo].[MasterReport] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_Product] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_ProductSubType] FOREIGN KEY ([ProductSubTypeId]) REFERENCES [dbo].[ProductSubType] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_ProductType] FOREIGN KEY ([ProductTypeId]) REFERENCES [dbo].[ProductType] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_Users] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_PayoverReportFilter_Users1] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

