CREATE TABLE [dbo].[ProductLine] (
    [Id]                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [ProductId]                     BIGINT          NOT NULL,
    [AdministratorId]               BIGINT          NULL,
    [ClaimsId]                      BIGINT          NULL,
    [OwnerId]                       BIGINT          NULL,
    [UnderwriterId]                 BIGINT          NULL,
    [InvoiceCompanyId]              BIGINT          NULL,
    [WebServiceCode]                NVARCHAR (100)  NULL,
    [ProductDisclosure]             NVARCHAR (200)  NULL,
    [PayoverAmount]                 DECIMAL (18, 2) NULL,
    [PayoverPercentage]             DECIMAL (18, 2) NULL,
    [AdminFee]                      DECIMAL (18, 2) NULL,
    [AdminPercentage]               DECIMAL (18, 2) NULL,
    [BinderFee]                     DECIMAL (18, 2) NULL,
    [BinderPercentage]              DECIMAL (18, 2) NULL,
    [CollectionFee]                 DECIMAL (18, 2) NULL,
    [CollectionPercentage]          DECIMAL (18, 2) NULL,
    [CommissionAmount]              DECIMAL (18, 2) NULL,
    [CommissionPercentage]          DECIMAL (18, 2) NULL,
    [DealerDocumentationFee]        DECIMAL (18, 2) NULL,
    [DealerDocumentationPercentage] DECIMAL (18, 2) NULL,
    [InspectionFee]                 DECIMAL (18, 2) NULL,
    [InspectionPercentage]          DECIMAL (18, 2) NULL,
    [PolicyFee]                     DECIMAL (18, 2) NULL,
    [PolicyPercentage]              DECIMAL (18, 2) NULL,
    [ValuationFee]                  DECIMAL (18, 2) NULL,
    [ValuationPercentage]           DECIMAL (18, 2) NULL,
    [DisplayType]                   INT             NULL,
    [CoverAmountTemplateId]         BIGINT          NULL,
    [ManufacturerTemplateId]        BIGINT          NULL,
    [ProductTemplateId]             BIGINT          NULL,
    [SupplierRecoveryAmount]        DECIMAL (18, 2) NULL,
    [BilltoCompanyId]               BIGINT          NULL,
    [StartDate]                     DATE            NOT NULL,
    [EndDate]                       DATE            NOT NULL,
    [CountryId]                     BIGINT          NULL,
    [IsActive]                      BIT             CONSTRAINT [ProductLine_DF_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]                   DATETIME        CONSTRAINT [ProductLine_DF_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                  DATETIME        NULL,
    [CreatedBy]                     INT             NOT NULL,
    [ModifiedBy]                    INT             NULL,
    CONSTRAINT [ProductLine_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_ProductLine_Template] FOREIGN KEY ([ProductTemplateId]) REFERENCES [dbo].[Template] ([Id]),
    CONSTRAINT [ProductLine_FK_CompanyCompanyTypeMappingAdministrator] FOREIGN KEY ([AdministratorId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductLine_FK_CompanyCompanyTypeMappingBilltoCompany] FOREIGN KEY ([BilltoCompanyId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductLine_FK_CompanyCompanyTypeMappingClaims] FOREIGN KEY ([ClaimsId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductLine_FK_CompanyCompanyTypeMappingInvoice] FOREIGN KEY ([InvoiceCompanyId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductLine_FK_CompanyCompanyTypeMappingOwner] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductLine_FK_CompanyCompanyTypeMappingUnderwriter] FOREIGN KEY ([UnderwriterId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductLine_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [ProductLine_FK_Product] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([Id]),
    CONSTRAINT [ProductLine_FK_TemplateCoverAmount] FOREIGN KEY ([CoverAmountTemplateId]) REFERENCES [dbo].[Template] ([Id]),
    CONSTRAINT [ProductLine_FK_TemplateMfg] FOREIGN KEY ([ManufacturerTemplateId]) REFERENCES [dbo].[Template] ([Id]),
    CONSTRAINT [ProductLine_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [ProductLine_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This table should be fill while creating product and also while creating new product line.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProductLine';

