CREATE TABLE [dbo].[ProductOptionPrice] (
    [Id]                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [ProductOptionId]        BIGINT          NOT NULL,
    [IsDepositInd]           BIT             CONSTRAINT [DF_ProductOptionPrice_IsDepositInd] DEFAULT ((0)) NOT NULL,
    [IsFinanceTermInd]       BIT             CONSTRAINT [DF_ProductOptionPrice_IsFinanceTermInd] DEFAULT ((0)) NOT NULL,
    [TermId]                 BIGINT          NULL,
    [MaximumTermId]          BIGINT          NULL,
    [MaximumTermQualifier]   INT             NULL,
    [DefaultCashTermId]      BIGINT          NULL,
    [MinimumCoverAmount]     DECIMAL (18, 2) NULL,
    [MaximumCoverAmount]     DECIMAL (18, 2) NULL,
    [MaximumCoverQualifier]  INT             NULL,
    [VehicleCondition]       INT             NULL,
    [VehiclePurpose]         INT             NULL,
    [MinimumPremiumPayable]  INT             NULL,
    [Price]                  DECIMAL (18, 2) NULL,
    [PayoverAmount]          DECIMAL (18, 2) NULL,
    [PayoverPercentage]      DECIMAL (18, 2) NULL,
    [AdminFee]               DECIMAL (18, 2) NULL,
    [AdminPercentage]        DECIMAL (18, 2) NULL,
    [BinderFee]              DECIMAL (18, 2) NULL,
    [BinderPercentage]       DECIMAL (18, 2) NULL,
    [CollectionFee]          DECIMAL (18, 2) NULL,
    [CollectionPercentage]   DECIMAL (18, 2) NULL,
    [CommissionAmount]       DECIMAL (18, 2) NULL,
    [CommissionPercentage]   DECIMAL (18, 2) NULL,
    [DealerDocumentationFee] DECIMAL (18, 2) NULL,
    [DealerDocPercentage]    DECIMAL (18, 2) NULL,
    [InspectionFee]          DECIMAL (18, 2) NULL,
    [InspectionPercentage]   DECIMAL (18, 2) NULL,
    [PolicyFee]              DECIMAL (18, 2) NULL,
    [PolicyPercentage]       DECIMAL (18, 2) NULL,
    [ValuationFee]           DECIMAL (18, 2) NULL,
    [ValuationPercentage]    DECIMAL (18, 2) NULL,
    [StartDate]              DATE            NOT NULL,
    [EndDate]                DATE            NOT NULL,
    [CountryId]              BIGINT          NULL,
    [IsActive]               BIT             CONSTRAINT [ProductOptionPrice_DF_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]            DATETIME        CONSTRAINT [ProductOptionPrice_DF_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]           DATETIME        NULL,
    [CreatedBy]              INT             NOT NULL,
    [ModifiedBy]             INT             NULL,
    [RatePercentage]         DECIMAL (18, 6) NULL,
    [MinimumPrice]           DECIMAL (18, 2) NULL,
    [IsVatIndicator]         BIT             NULL,
    [CalculationTemplate]    INT             NULL,
    [AllowAutoSelect]        BIT             NULL,
    [CostPercentage]         DECIMAL (18, 6) NULL,
    CONSTRAINT [ProductOptionPrice_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [ProductOptionPrice_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [ProductOptionPrice_FK_FinanceTermDefaultCashTerm] FOREIGN KEY ([DefaultCashTermId]) REFERENCES [dbo].[FinanceTerm] ([Id]),
    CONSTRAINT [ProductOptionPrice_FK_FinanceTermMaxTerm] FOREIGN KEY ([MaximumTermId]) REFERENCES [dbo].[FinanceTerm] ([Id]),
    CONSTRAINT [ProductOptionPrice_FK_FinanceTermTerm] FOREIGN KEY ([TermId]) REFERENCES [dbo].[FinanceTerm] ([Id]),
    CONSTRAINT [ProductOptionPrice_FK_ProductOption] FOREIGN KEY ([ProductOptionId]) REFERENCES [dbo].[ProductOption] ([Id]),
    CONSTRAINT [ProductOptionPrice_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [ProductOptionPrice_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This table store product option price inside product option.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'ProductOptionPrice';

