CREATE TABLE [dbo].[ProductDetailsReportFilterMapping] (
    [Id]                           BIGINT   IDENTITY (1, 1) NOT NULL,
    [ProductDetailsReportFilterId] BIGINT   NOT NULL,
    [GroupId]                      BIGINT   NULL,
    [BranchId]                     BIGINT   NULL,
    [ProductId]                    BIGINT   NULL,
    [AdministratorId]              BIGINT   NULL,
    [ClaimId]                      BIGINT   NULL,
    [OwnerId]                      BIGINT   NULL,
    [UnderwriterId]                BIGINT   NULL,
    [CriteriaEnum]                 INT      NULL,
    [IsActive]                     BIT      CONSTRAINT [DF_ProductDetailsReportMapping_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]                  DATETIME NULL,
    [ModifiedDate]                 DATETIME NULL,
    [CreatedBy]                    INT      NULL,
    [ModifiedBy]                   INT      NULL,
    CONSTRAINT [ProductDetailsReportFilterMapping_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_Branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[Branch] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_CompanyCompanyTypeMappingAdministratorId] FOREIGN KEY ([AdministratorId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_CompanyCompanyTypeMappingClaimId] FOREIGN KEY ([ClaimId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_CompanyCompanyTypeMappingOwnerId] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_CompanyCompanyTypeMappingUnderwriterId] FOREIGN KEY ([UnderwriterId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_Product] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Product] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_ProductDetailsReportFilter] FOREIGN KEY ([ProductDetailsReportFilterId]) REFERENCES [dbo].[ProductDetailsReportFilter] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [ProductDetailsReportFilterMapping_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

