CREATE TABLE [dbo].[Product] (
    [Id]                            BIGINT          IDENTITY (1, 1) NOT NULL,
    [ProductTypeId]                 BIGINT          NOT NULL,
    [ProductSubTypeId]              BIGINT          NOT NULL,
    [ProductName]                   NVARCHAR (100)  NOT NULL,
    [IsInsuranceProduct]            BIT             CONSTRAINT [Product_DF_IsInsuranceProduct] DEFAULT ((0)) NOT NULL,
    [AdministratorId]               BIGINT          NULL,
    [ClaimsId]                      BIGINT          NULL,
    [OwnerId]                       BIGINT          NULL,
    [UnderwriterId]                 BIGINT          NULL,
    [PaymentType]                   INT             NOT NULL,
    [IsTyreInfoRequired]            BIT             CONSTRAINT [Product_DF_TyreInfoRequired] DEFAULT ((0)) NOT NULL,
    [IsVehicleDamageInfoRequired]   BIT             CONSTRAINT [Product_DF_VehicleDamageInfoRequired] DEFAULT ((0)) NOT NULL,
    [IsEnableProductNote]           BIT             CONSTRAINT [Product_DF_EnableProductNote] DEFAULT ((0)) NOT NULL,
    [IsReferenceNoRequired]         BIT             CONSTRAINT [Product_DF_ReferenceNoRequired] DEFAULT ((0)) NOT NULL,
    [IsPayByCash]                   BIT             CONSTRAINT [Product_DF_PayByCash] DEFAULT ((0)) NOT NULL,
    [WebServiceCode]                NVARCHAR (100)  NULL,
    [PayoverAmount]                 DECIMAL (18, 2) NULL,
    [PayoverPercentage]             DECIMAL (18, 2) NULL,
    [AdminFee]                      DECIMAL (18, 2) NULL,
    [AdminPercentage]               DECIMAL (18, 2) NULL,
    [BinderFee]                     DECIMAL (18, 2) NULL,
    [BinderPercentage]              DECIMAL (18, 2) NULL,
    [CollectionFee]                 DECIMAL (18, 2) NULL,
    [CollectionPercentage]          DECIMAL (18, 2) NULL,
    [CommissionAmount]              DECIMAL (18, 2) NULL,
    [CommissionPercentage]          DECIMAL (18, 2) NULL,
    [DealerDocumentationFee]        DECIMAL (18, 2) NULL,
    [DealerDocumentationPercentage] DECIMAL (18, 2) NULL,
    [InspectionFee]                 DECIMAL (18, 2) NULL,
    [InspectionPercentage]          DECIMAL (18, 2) NULL,
    [PolicyFee]                     DECIMAL (18, 2) NULL,
    [PolicyPercentage]              DECIMAL (18, 2) NULL,
    [ValuationFee]                  DECIMAL (18, 2) NULL,
    [ValuationPercentage]           DECIMAL (18, 2) NULL,
    [DisplayType]                   INT             NULL,
    [ManufacturerTemplateId]        BIGINT          NULL,
    [ProductTemplateId]             BIGINT          NULL,
    [SMSTemplateId]                 BIGINT          NULL,
    [IsEditablePayover]             BIT             CONSTRAINT [Product_DF_EditablePayover] DEFAULT ((0)) NOT NULL,
    [IsAvailableInPackage]          BIT             CONSTRAINT [Product_DF_AvailableInPackage] DEFAULT ((0)) NOT NULL,
    [SupplierRecoveryAmount]        DECIMAL (18, 2) NULL,
    [BilltoCompanyId]               BIGINT          NULL,
    [Wording]                       NVARCHAR (150)  NULL,
    [StartDate]                     DATE            NULL,
    [EndDate]                       DATE            NULL,
    [ProductCopyId]                 BIGINT          NULL,
    [CountryId]                     BIGINT          NULL,
    [IsActive]                      BIT             CONSTRAINT [Product_DF_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]                   DATETIME        CONSTRAINT [Product_DF_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                  DATETIME        NULL,
    [CreatedBy]                     INT             NOT NULL,
    [ModifiedBy]                    INT             NULL,
    [TransactionFormulaId]          BIGINT          NULL,
    [MinimumPrice]                  DECIMAL (18, 2) NULL,
    CONSTRAINT [Product_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [Product_FK_CompanyCompanyTypeBillToCompany] FOREIGN KEY ([BilltoCompanyId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [Product_FK_CompanyCompanyTypeMappingAdministrator] FOREIGN KEY ([AdministratorId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [Product_FK_CompanyCompanyTypeMappingClaims] FOREIGN KEY ([ClaimsId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [Product_FK_CompanyCompanyTypeMappingOwner] FOREIGN KEY ([OwnerId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [Product_FK_CompanyCompanyTypeMappingUnderwriter] FOREIGN KEY ([UnderwriterId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [Product_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [Product_FK_ProductSubType] FOREIGN KEY ([ProductSubTypeId]) REFERENCES [dbo].[ProductSubType] ([Id]),
    CONSTRAINT [Product_FK_ProductType] FOREIGN KEY ([ProductTypeId]) REFERENCES [dbo].[ProductType] ([Id]),
    CONSTRAINT [Product_FK_TemplateManufacturer] FOREIGN KEY ([ManufacturerTemplateId]) REFERENCES [dbo].[Template] ([Id]),
    CONSTRAINT [Product_FK_TemplateProduct] FOREIGN KEY ([ProductTemplateId]) REFERENCES [dbo].[Template] ([Id]),
    CONSTRAINT [Product_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [Product_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This table store the Product of system.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Product';

