CREATE TABLE [dbo].[RolloverDetails] (
    [Id]                 BIGINT          IDENTITY (1, 1) NOT NULL,
    [GroupId]            BIGINT          NULL,
    [BranchId]           BIGINT          NULL,
    [BranchCode]         NVARCHAR (50)   NULL,
    [BusinessManagerId]  INT             NULL,
    [TransactionTypeId]  BIGINT          NULL,
    [VehicleConditionId] BIGINT          NULL,
    [ProductTypeId]      BIGINT          NULL,
    [ProductSubTypeId]   BIGINT          NULL,
    [FinanceCompanyId]   BIGINT          NULL,
    [AmountExclVat]      DECIMAL (18, 2) NULL,
    [VatAmount]          DECIMAL (18, 2) NULL,
    [AmountInclVat]      DECIMAL (18, 2) NULL,
    [Note]               NVARCHAR (4000) NULL,
    [ReceiptDate]        DATE            NULL,
    [IsActive]           BIT             CONSTRAINT [DF_RolloverDetails_IsActive] DEFAULT ((1)) NULL,
    [CreatedDate]        DATETIME        CONSTRAINT [DF_RolloverDetails_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]       DATETIME        NULL,
    [CreatedBy]          INT             NULL,
    [ModifiedBy]         INT             NULL,
    CONSTRAINT [RolloverDetails_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [RolloverDetails_FK_Branch] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[Branch] ([Id]),
    CONSTRAINT [RolloverDetails_FK_CompanyCompanyTypeMapping] FOREIGN KEY ([FinanceCompanyId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [RolloverDetails_FK_Group] FOREIGN KEY ([GroupId]) REFERENCES [dbo].[Group] ([Id]),
    CONSTRAINT [RolloverDetails_FK_ProductSubType] FOREIGN KEY ([ProductSubTypeId]) REFERENCES [dbo].[ProductSubType] ([Id]),
    CONSTRAINT [RolloverDetails_FK_ProductType] FOREIGN KEY ([ProductTypeId]) REFERENCES [dbo].[ProductType] ([Id]),
    CONSTRAINT [RolloverDetails_FK_StaticValueTransactionTypeId] FOREIGN KEY ([TransactionTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [RolloverDetails_FK_StaticValueVehicleConditionId] FOREIGN KEY ([VehicleConditionId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [RolloverDetails_FK_UsersBusinessManagerId] FOREIGN KEY ([BusinessManagerId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [RolloverDetails_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [RolloverDetails_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

