CREATE TABLE [dbo].[TransactionBankingDetails] (
    [Id]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [BankId]                      BIGINT          NULL,
    [BranchName]                  NVARCHAR (200)  NULL,
    [AccountType]                 BIGINT          NULL,
    [AccountNo]                   NVARCHAR (200)  NULL,
    [LoanType]                    BIGINT          NULL,
    [IsSalaryTransferedToBank]    BIT             NULL,
    [LoanOutstanding]             DECIMAL (18, 2) NULL,
    [Emirate]                     NVARCHAR (200)  NULL,
    [NoOfYearsAccountHeld]        INT             NULL,
    [IsActive]                    BIT             CONSTRAINT [DF__Transacti__IsAct__3871AF88] DEFAULT ((1)) NOT NULL,
    [CreatedDate]                 DATETIME        CONSTRAINT [DF__Transacti__Creat__3965D3C1] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                DATETIME        NULL,
    [CreatedBy]                   INT             NOT NULL,
    [ModifiedBy]                  INT             NULL,
    [CountryId]                   BIGINT          NULL,
    [BranchCode]                  NVARCHAR (50)   NULL,
    [BranchType]                  NVARCHAR (50)   NULL,
    [NameOfAccountHolder]         NVARCHAR (100)  NULL,
    [DateOfAccountOpened]         DATE            NULL,
    [TransactionId]               BIGINT          NULL,
    [MonthlyInstalment]           DECIMAL (18, 2) NULL,
    [CreditCardTypeId]            BIGINT          NULL,
    [CreditCardNumber]            NVARCHAR (50)   NULL,
    [CreditCardDateofIssue]       DATE            NULL,
    [CreditCardDateofExpiry]      DATE            NULL,
    [AccountDetailsType]          INT             NULL,
    [IsIncludeDetails]            BIT             DEFAULT ((0)) NULL,
    [DebitOrderDate]              DATE            NULL,
    [IsSendDebitOrderDetails]     BIT             NULL,
    [DebitOrderStartDate]         DATE            NULL,
    [DebitOrderEndDate]           DATE            NULL,
    [NoOfPaymentPeriods]          INT             NULL,
    [DebitAmount]                 DECIMAL (18, 8) NULL,
    [MaximumAmount]               DECIMAL (18, 8) NULL,
    [DebitOrderCompanyID]         BIGINT          NULL,
    [IsDebitOrder]                BIT             NULL,
    [CreditCardOutStanding]       DECIMAL (18, 8) NULL,
    [FirstEMIDate]                DATE            NULL,
    [PaymentMethod]               BIGINT          NULL,
    [AccountName]                 NVARCHAR (200)  NULL,
    [IBANNumber]                  NVARCHAR (200)  NULL,
    [NoOfEMIsForObligation]       INT             NULL,
    [RepaymentAccount]            BIT             NULL,
    [IsExistingCASAAccountNumber] BIT             NULL,
    [ExistingCASAAccountNumber]   NVARCHAR (200)  NULL,
    [IsDownPaymentAccount]        BIT             NULL,
    [BranchId]                    BIGINT          NULL,
    [IsFeeCollectionbyDebitOrder] BIT             NULL,
    [SalaryPayDate]               DATETIME        NULL,
    [SalaryPayDay]                INT             NULL,
    CONSTRAINT [ClientBankingDetails_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_InceptTransactionBankingDetails_StaticValue_LoanType] FOREIGN KEY ([LoanType]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionBankingDetails_StaticValue_LoanType] FOREIGN KEY ([LoanType]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_PaymentMethod] FOREIGN KEY ([PaymentMethod]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_StaticValueAccountType] FOREIGN KEY ([AccountType]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_StaticValueBankId] FOREIGN KEY ([BankId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_StaticValueBranchId] FOREIGN KEY ([BranchId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_StaticValueCreditCardTypeId] FOREIGN KEY ([CreditCardTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_Transaction] FOREIGN KEY ([TransactionId]) REFERENCES [dbo].[Transaction] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionBankingDetails_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

