CREATE TABLE [dbo].[TransactionClient] (
    [Id]                             BIGINT          IDENTITY (1, 1) NOT NULL,
    [TitleId]                        BIGINT          NULL,
    [FirstName]                      NVARCHAR (100)  NULL,
    [MiddleName]                     NVARCHAR (100)  NULL,
    [LastName]                       NVARCHAR (100)  NULL,
    [Initials]                       NVARCHAR (50)   NULL,
    [DateofBirth]                    DATE            NULL,
    [PlaceOfBirth]                   NVARCHAR (200)  NULL,
    [Nationality]                    BIGINT          NULL,
    [NoofDependents]                 INT             NULL,
    [MaritalStatusId]                BIGINT          NULL,
    [MarriageDate]                   DATE            NULL,
    [GenderId]                       BIGINT          NULL,
    [MothersMaidenName]              NVARCHAR (200)  NULL,
    [UAEResidentSince]               DATE            NULL,
    [IDTypeId]                       BIGINT          NULL,
    [IDNumber]                       NVARCHAR (100)  NULL,
    [PassportNo]                     NVARCHAR (100)  NULL,
    [PassportIssueDate]              DATE            NULL,
    [PassportExpiryDate]             DATE            NULL,
    [PassportIssuePlace]             NVARCHAR (200)  NULL,
    [VisaNo]                         NVARCHAR (100)  NULL,
    [VisaIssueDate]                  DATE            NULL,
    [VisaExpiryDate]                 DATE            NULL,
    [VisaIssuePlace]                 NVARCHAR (200)  NULL,
    [EmiratesIdNo]                   NVARCHAR (200)  NULL,
    [EmiratesIdIssueDate]            DATE            NULL,
    [EmiratesIdExpiryDate]           DATE            NULL,
    [EmiratesIdIssuePlace]           NVARCHAR (200)  NULL,
    [DriversLicenceNo]               NVARCHAR (100)  NULL,
    [DriversLicenceIssueDate]        DATE            NULL,
    [DriversLicenceExpiryDate]       DATE            NULL,
    [DriversLicenceIssuePlace]       NVARCHAR (200)  NULL,
    [UAEDrivingLicenceNo]            NVARCHAR (100)  NULL,
    [PreferredName]                  NVARCHAR (100)  NULL,
    [Mobile]                         NVARCHAR (100)  NULL,
    [AlternativeMobile]              NVARCHAR (100)  NULL,
    [HomePhoneCode]                  NVARCHAR (10)   NULL,
    [HomePhoneNumber]                NVARCHAR (50)   NULL,
    [WorkPhoneCode]                  NVARCHAR (10)   NULL,
    [WorkPhoneNumber]                NVARCHAR (50)   NULL,
    [FaxCode]                        NVARCHAR (10)   NULL,
    [FaxNumber]                      NVARCHAR (50)   NULL,
    [ContactNumberInHomeCountry]     NVARCHAR (50)   NULL,
    [EmailAddress]                   NVARCHAR (100)  NULL,
    [IsSMSAlertRequired]             BIT             CONSTRAINT [DF_TransactionClient_IsSMSAlertRequired] DEFAULT ((0)) NULL,
    [PreferedMailingAddress]         BIGINT          NULL,
    [NumberForSMSAlert]              NVARCHAR (100)  NULL,
    [PhyAddBuildingName]             NVARCHAR (200)  NULL,
    [PhyAddFlatNo]                   NVARCHAR (50)   NULL,
    [PhyAddUnitNo]                   NVARCHAR (50)   NULL,
    [PhyAddNearestLandmark]          NVARCHAR (200)  NULL,
    [PhyAddArea]                     NVARCHAR (100)  NULL,
    [PhyAddStreetName]               NVARCHAR (200)  NULL,
    [PostAddPOBoxNo]                 NVARCHAR (200)  NULL,
    [PhyAddEmirate]                  BIGINT          NULL,
    [PhyAddCity]                     NVARCHAR (200)  NULL,
    [PhyAddState]                    NVARCHAR (100)  NULL,
    [PhyAddCountryId]                BIGINT          NULL,
    [PhyAddZipCode]                  NVARCHAR (50)   NULL,
    [PostAddEmirate]                 BIGINT          NULL,
    [ResidentialStatus]              BIGINT          NULL,
    [NoOfYearsAtPesentAddress]       NVARCHAR (50)   NULL,
    [PostAddCountryId]               BIGINT          NULL,
    [RentPerMonth]                   DECIMAL (18, 2) NULL,
    [AddressInHomeCountry]           NVARCHAR (500)  NULL,
    [HomeCountryId]                  BIGINT          NULL,
    [BankingDetailsId]               BIGINT          NULL,
    [CustomerType]                   INT             NOT NULL,
    [NameOfKin]                      NVARCHAR (100)  NULL,
    [AddressOfKin]                   NVARCHAR (200)  NULL,
    [ContactOfKin]                   NVARCHAR (50)   NULL,
    [CountryId]                      BIGINT          NULL,
    [IsActive]                       BIT             CONSTRAINT [TransactionClient_DF_IsActive] DEFAULT ((1)) NOT NULL,
    [CreatedDate]                    DATETIME        CONSTRAINT [TransactionClient_DF_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                   DATETIME        NULL,
    [CreatedBy]                      INT             NOT NULL,
    [ModifiedBy]                     INT             NULL,
    [IsGuarantorApplication]         BIT             NULL,
    [RegularDriver]                  BIT             NULL,
    [ConditionsResidentPermit]       NVARCHAR (100)  NULL,
    [LanguageId]                     BIGINT          NULL,
    [MarrageTypeId]                  BIGINT          NULL,
    [SpousesName]                    NVARCHAR (100)  NULL,
    [SpousesBirthDate]               DATE            NULL,
    [PhyAddSurburb]                  NVARCHAR (50)   NULL,
    [PhyAddTown]                     NVARCHAR (50)   NULL,
    [PostAddSurburb]                 NVARCHAR (50)   NULL,
    [PostAddTown]                    NVARCHAR (50)   NULL,
    [SpecifyResidentialStatus]       NVARCHAR (100)  NULL,
    [PreviousHomeAddress]            NVARCHAR (100)  NULL,
    [PreferredCallTime]              BIGINT          NULL,
    [CompanyName]                    NVARCHAR (MAX)  NULL,
    [ComNatureOfBusiness]            BIGINT          NULL,
    [CompanyStartDate]               DATE            NULL,
    [ComTradeLicenceStartDate]       DATE            NULL,
    [ComTradeLicenceExpiryDate]      DATE            NULL,
    [ComVATNumber]                   NVARCHAR (50)   NULL,
    [ComPhyAddBuildingName]          NVARCHAR (200)  NULL,
    [ComPhyAddStreetName]            NVARCHAR (100)  NULL,
    [ComPhyAddEmirate]               BIGINT          NULL,
    [ComPhyAddPostCode]              NVARCHAR (100)  NULL,
    [ComPhyAddCountryId]             BIGINT          NULL,
    [ComTradingAs]                   NVARCHAR (50)   NULL,
    [ComRegistrationNumber]          NVARCHAR (50)   NULL,
    [ComNoOfYearsInBusiness]         INT             NULL,
    [ComLandlord]                    NVARCHAR (100)  NULL,
    [ComHoldingCompany]              NVARCHAR (100)  NULL,
    [ComAssociatedCompany]           NVARCHAR (200)  NULL,
    [ComSubsidaryCompany]            NVARCHAR (200)  NULL,
    [ComCompanyRepresentative]       NVARCHAR (100)  NULL,
    [ComFloorNo]                     INT             NULL,
    [ComYearsAtCurrentAddress]       INT             NULL,
    [ComEmirate]                     BIGINT          NULL,
    [PhyAdd1]                        NVARCHAR (200)  NULL,
    [PhyAdd2]                        NVARCHAR (200)  NULL,
    [PhyAdd3]                        NVARCHAR (200)  NULL,
    [PostAdd1]                       NVARCHAR (200)  NULL,
    [PostAdd2]                       NVARCHAR (200)  NULL,
    [PostAdd3]                       NVARCHAR (200)  NULL,
    [FinanceStatus]                  BIGINT          NULL,
    [FinanceStatusNotes]             NVARCHAR (500)  NULL,
    [ConditionsOfResidentsPermit]    NVARCHAR (500)  NULL,
    [BusinessTypeId]                 BIGINT          NULL,
    [QualificationId]                BIGINT          NULL,
    [PermitNumber]                   NVARCHAR (100)  NULL,
    [PermitIssueDate]                DATE            NULL,
    [PermitExpiryDate]               DATE            NULL,
    [IdIssueDate]                    DATE            NULL,
    [IdExpiryDate]                   DATE            NULL,
    [SpecifyMaritalStatus]           NVARCHAR (100)  NULL,
    [EthnicGroup]                    BIGINT          NULL,
    [MarketingSource]                BIGINT          NULL,
    [ClaimFreeGroup]                 BIGINT          NULL,
    [IsCompanyVATRegistered]         BIT             NULL,
    [PhyAdd4]                        NVARCHAR (200)  NULL,
    [PhyAddCode]                     NVARCHAR (100)  NULL,
    [PostAdd4]                       NVARCHAR (200)  NULL,
    [PostAddCode]                    NVARCHAR (100)  NULL,
    [IsCompanyBlackOwned]            BIT             NULL,
    [IsCompanyBalanceSheet]          BIT             NULL,
    [CompanyFinancialYear]           NVARCHAR (200)  NULL,
    [CompanyTurnover]                DECIMAL (18, 4) NULL,
    [CompanyTotalAssets]             DECIMAL (18, 4) NULL,
    [NoOfMonthsAtPesentAddress]      NVARCHAR (50)   NULL,
    [ComPhyAdd1]                     NVARCHAR (200)  NULL,
    [ComPhyAdd2]                     NVARCHAR (200)  NULL,
    [ComPhyAdd3]                     NVARCHAR (200)  NULL,
    [ComPhyAdd4]                     NVARCHAR (200)  NULL,
    [ComPhyAddCode]                  NVARCHAR (100)  NULL,
    [HomeCountryAddress1]            NVARCHAR (200)  NULL,
    [HomeCountryAddress2]            NVARCHAR (200)  NULL,
    [HomeCountryAddress3]            NVARCHAR (200)  NULL,
    [HomeCountryAddress4]            NVARCHAR (200)  NULL,
    [HomeCountryAddressCode]         NVARCHAR (100)  NULL,
    [PreferredLanguage]              NVARCHAR (200)  NULL,
    [TradeLicenseNumber]             NVARCHAR (200)  NULL,
    [IsSpouseDetailsIncluded]        BIT             DEFAULT ((0)) NULL,
    [ComPhyAddMakaniNumber]          NVARCHAR (200)  NULL,
    [OfficeBuildingName]             NVARCHAR (200)  NULL,
    [OfficeStreetName]               NVARCHAR (200)  NULL,
    [OfficeEmirate]                  BIGINT          NULL,
    [OfficeCountry]                  BIGINT          NULL,
    [OfficeNearestLandmark]          NVARCHAR (200)  NULL,
    [OfficeMakaniNumber]             NVARCHAR (200)  NULL,
    [ComNumberofFleetVehicles]       BIGINT          NULL,
    [ComNumberofMortgagedVehicles]   BIGINT          NULL,
    [IsClientClaimedIn12Months]      BIT             NULL,
    [IsStaffIndicator]               BIT             NULL,
    [NewInCountry]                   BIT             NULL,
    [FamilyName]                     NVARCHAR (200)  NULL,
    [FirstNameInArabic]              NVARCHAR (200)  NULL,
    [MiddleNameInArabic]             NVARCHAR (200)  NULL,
    [LastNameInArabic]               NVARCHAR (200)  NULL,
    [FamilyNameInArabic]             NVARCHAR (200)  NULL,
    [IsResident]                     BIT             NULL,
    [ComNoOfPeopleEmployed]          INT             NULL,
    [ComTradeLicensePlaceofIssue]    NVARCHAR (200)  NULL,
    [AreaName]                       NVARCHAR (200)  NULL,
    [VillaOrApartmentNumber]         NVARCHAR (50)   NULL,
    [AreaCodeId]                     BIGINT          NULL,
    [OfficeTelephonenumberExtension] NVARCHAR (10)   NULL,
    [CityId]                         BIGINT          NULL,
    [EmiratesCardNumber]             NVARCHAR (50)   NULL,
    [EmiratesCardPhoto]              NVARCHAR (MAX)  NULL,
    [IsEmiratesCardSwiped]           BIT             NULL,
    [ResidencyStatus]                BIGINT          NULL,
    [IsUpdateStatustoTransaction]    BIT             NULL,
    CONSTRAINT [TransactionClient_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TransactionClient_StaticValueClaimsFreeGroup] FOREIGN KEY ([ClaimFreeGroup]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionClient_StaticValueMarketingSource] FOREIGN KEY ([MarketingSource]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionClient_StaticValuePreferedMailingAddress] FOREIGN KEY ([PreferedMailingAddress]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_CountryComPhyAddCountryId] FOREIGN KEY ([ComPhyAddCountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_CountryHomeCountryId] FOREIGN KEY ([HomeCountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_CountryNationality] FOREIGN KEY ([Nationality]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_CountryPhyAdd] FOREIGN KEY ([PhyAddCountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_CountryPhyAddCountryId] FOREIGN KEY ([PhyAddCountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_CountryPostAdd] FOREIGN KEY ([PostAddCountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_IdType] FOREIGN KEY ([IDTypeId]) REFERENCES [dbo].[IdType] ([Id]),
    CONSTRAINT [TransactionClient_FK_OfficeCountry] FOREIGN KEY ([OfficeCountry]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionClient_FK_OfficeEmirate] FOREIGN KEY ([OfficeEmirate]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueAreaCodeId] FOREIGN KEY ([AreaCodeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueBusinessTypeId] FOREIGN KEY ([BusinessTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueCityId] FOREIGN KEY ([CityId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueComEmirate] FOREIGN KEY ([ComEmirate]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueComNatureOfBusiness] FOREIGN KEY ([ComNatureOfBusiness]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueComPhyAddEmirate] FOREIGN KEY ([ComPhyAddEmirate]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueEthnicGroup] FOREIGN KEY ([EthnicGroup]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueFinanceStatus] FOREIGN KEY ([FinanceStatus]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueGender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueLanguage] FOREIGN KEY ([LanguageId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueMaritalStatus] FOREIGN KEY ([MaritalStatusId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueMarrageType] FOREIGN KEY ([MarrageTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValuePhyAddEmirate] FOREIGN KEY ([PhyAddEmirate]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValuePostAddEmirate] FOREIGN KEY ([PostAddEmirate]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValuePreferredCallTime] FOREIGN KEY ([PreferredCallTime]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueQualificationId] FOREIGN KEY ([QualificationId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueResidenctStatus] FOREIGN KEY ([ResidencyStatus]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueResidentialStatus] FOREIGN KEY ([ResidentialStatus]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_StaticValueTitle] FOREIGN KEY ([TitleId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionClient_FK_TransactionBankingDetails] FOREIGN KEY ([BankingDetailsId]) REFERENCES [dbo].[TransactionBankingDetails] ([Id]),
    CONSTRAINT [TransactionClient_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionClient_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This table is for Transaction CLient details and driver Details.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TransactionClient';


GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'0-Male,1-Female', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'TransactionClient', @level2type = N'COLUMN', @level2name = N'GenderId';

