CREATE TABLE [dbo].[TransactionReportFilter] (
    [Id]                                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [IncludeUninceptedDeals]                  BIT             DEFAULT ((0)) NULL,
    [IncludeInceptedDeals]                    BIT             DEFAULT ((0)) NULL,
    [StartDate]                               DATE            NULL,
    [EndDate]                                 DATE            NULL,
    [IsCreateDate]                            BIT             CONSTRAINT [DF_TransactionReportFilter_IsCreateDate] DEFAULT ((0)) NULL,
    [IsInceptDate]                            BIT             CONSTRAINT [DF_TransactionReportFilter_IsInceptDate] DEFAULT ((0)) NULL,
    [IsInvoiceDate]                           BIT             CONSTRAINT [DF_TransactionReportFilter_IsInvoiceDate] DEFAULT ((0)) NULL,
    [IsInvoicePaidDate]                       BIT             CONSTRAINT [DF_TransactionReportFilter_IsInvoicePaidDate] DEFAULT ((0)) NULL,
    [IsEmailReport]                           BIT             CONSTRAINT [DF_TransactionReportFilter_IsEmailReport] DEFAULT ((0)) NULL,
    [Email]                                   NVARCHAR (100)  NULL,
    [ReportFilePath]                          NVARCHAR (200)  NULL,
    [CopiedFrom]                              BIGINT          NULL,
    [CountryId]                               BIGINT          NULL,
    [ReportFormat]                            TINYINT         NULL,
    [IsShareDetailsWithinCompany]             INT             NULL,
    [IsShareDetailsAmongPartner]              INT             NULL,
    [IsReceiveMarketingInfo]                  INT             NULL,
    [IsDisclosureofPersonalInfo]              INT             NULL,
    [IsDebitOrderInformationAndAuthorization] INT             NULL,
    [IsActive]                                BIT             DEFAULT ((1)) NOT NULL,
    [CreatedDate]                             DATETIME        DEFAULT (getutcdate()) NULL,
    [ModifiedDate]                            DATETIME        NULL,
    [CreatedBy]                               INT             NULL,
    [ModifiedBy]                              INT             NULL,
    [FileSize]                                DECIMAL (18, 2) NULL,
    [MasterReportId]                          BIGINT          NULL,
    [IsRetail]                                BIT             NOT NULL,
    [IncludeBankingDetails]                   BIT             DEFAULT ((0)) NULL,
    [ReportColumnFilePath]                    NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_TransactionReportFilter] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TransactionReportFilter_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_TransactionReportFilter_MasterReport] FOREIGN KEY ([MasterReportId]) REFERENCES [dbo].[MasterReport] ([Id]),
    CONSTRAINT [FK_TransactionReportFilter_Users_CreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_TransactionReportFilter_Users_ModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

