CREATE TABLE [dbo].[TransactionItemHistory] (
    [Id]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [ApplicationHistoryId]  BIGINT          NOT NULL,
    [ItemId]                BIGINT          NOT NULL,
    [TransactionId]         BIGINT          NULL,
    [ItemTypeId]            BIGINT          NULL,
    [ItemUseId]             BIGINT          NULL,
    [ItemDescription]       NVARCHAR (2000) NULL,
    [ItemCode]              NVARCHAR (100)  NULL,
    [ItemSerialNumber]      NVARCHAR (100)  NULL,
    [ItemCost]              DECIMAL (18, 8) NULL,
    [ItemRetailValue]       DECIMAL (18, 8) NULL,
    [ItemQuantity]          INT             NULL,
    [TotalItemsRetailValue] DECIMAL (18, 8) NULL,
    [LoanAmountAppliedFor]  DECIMAL (18, 8) NULL,
    [Discount]              DECIMAL (18, 8) NULL,
    [Notes]                 NVARCHAR (2000) NULL,
    [IsActive]              BIT             DEFAULT ((1)) NOT NULL,
    [CountryId]             BIGINT          NULL,
    [CreatedBy]             INT             NULL,
    [ModifiedBy]            INT             NULL,
    [CreatedDate]           DATETIME        DEFAULT (getutcdate()) NULL,
    [ModifiedDate]          DATETIME        NULL,
    [MaxLoanApproved]       DECIMAL (18, 8) NULL,
    [ItemInvoiceNo]         NVARCHAR (50)   NULL,
    [ItemStockNo]           NVARCHAR (50)   NULL,
    [ItemInvoiceDate]       DATETIME        NULL,
    [ItemInvoicePaidDate]   DATETIME        NULL,
    [ItemDeliveryDate]      DATETIME        NULL,
    [IncludeInLead]         BIT             NULL,
    CONSTRAINT [PK_TransactionItemHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

