CREATE TABLE [dbo].[TransactionClientHistory] (
    [Id]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [ApplicationHistoryId]         BIGINT          NOT NULL,
    [ClientId]                     BIGINT          NOT NULL,
    [TitleId]                      BIGINT          NULL,
    [FirstName]                    NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [MiddleName]                   NVARCHAR (100)  NULL,
    [LastName]                     NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [Initials]                     NVARCHAR (50)   NULL,
    [DateofBirth]                  DATE            NULL,
    [PlaceOfBirth]                 NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [Nationality]                  BIGINT          NULL,
    [NoofDependents]               INT             NULL,
    [MaritalStatusId]              BIGINT          NULL,
    [MarriageDate]                 DATE            NULL,
    [GenderId]                     BIGINT          NULL,
    [MothersMaidenName]            NVARCHAR (200)  NULL,
    [UAEResidentSince]             DATE            NULL,
    [IDTypeId]                     BIGINT          NULL,
    [IDNumber]                     NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PassportNo]                   NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PassportIssueDate]            DATE            NULL,
    [PassportExpiryDate]           DATE            NULL,
    [PassportIssuePlace]           NVARCHAR (200)  NULL,
    [VisaNo]                       NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [VisaIssueDate]                DATE            NULL,
    [VisaExpiryDate]               DATE            NULL,
    [VisaIssuePlace]               NVARCHAR (200)  NULL,
    [EmiratesIdNo]                 NVARCHAR (200)  COLLATE Latin1_General_BIN2 NULL,
    [EmiratesIdIssueDate]          DATE            NULL,
    [EmiratesIdExpiryDate]         DATE            NULL,
    [EmiratesIdIssuePlace]         NVARCHAR (200)  NULL,
    [DriversLicenceNo]             NVARCHAR (100)  NULL,
    [DriversLicenceIssueDate]      DATE            NULL,
    [DriversLicenceExpiryDate]     DATE            NULL,
    [DriversLicenceIssuePlace]     NVARCHAR (200)  NULL,
    [UAEDrivingLicenceNo]          NVARCHAR (100)  NULL,
    [PreferredName]                NVARCHAR (100)  NULL,
    [Mobile]                       NVARCHAR (100)  NULL,
    [AlternativeMobile]            NVARCHAR (100)  NULL,
    [HomePhoneCode]                NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [HomePhoneNumber]              NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneCode]                NVARCHAR (10)   COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneNumber]              NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [FaxCode]                      NVARCHAR (10)   NULL,
    [FaxNumber]                    NVARCHAR (50)   NULL,
    [ContactNumberInHomeCountry]   NVARCHAR (50)   NULL,
    [EmailAddress]                 NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [IsSMSAlertRequired]           BIT             NULL,
    [PreferedMailingAddress]       INT             NULL,
    [NumberForSMSAlert]            NVARCHAR (100)  NULL,
    [PhyAddBuildingName]           NVARCHAR (200)  NULL,
    [PhyAddFlatNo]                 NVARCHAR (50)   NULL,
    [PhyAddUnitNo]                 NVARCHAR (50)   NULL,
    [PhyAddNearestLandmark]        NVARCHAR (200)  NULL,
    [PhyAddArea]                   NVARCHAR (100)  NULL,
    [PhyAddStreetName]             NVARCHAR (200)  NULL,
    [PostAddPOBoxNo]               NVARCHAR (200)  NULL,
    [PhyAddEmirate]                BIGINT          NULL,
    [PhyAddCity]                   NVARCHAR (200)  NULL,
    [PhyAddState]                  NVARCHAR (100)  NULL,
    [PhyAddCountryId]              BIGINT          NULL,
    [PhyAddZipCode]                NVARCHAR (50)   NULL,
    [PostAddEmirate]               BIGINT          NULL,
    [ResidentialStatus]            BIGINT          NULL,
    [NoOfYearsAtPesentAddress]     NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [PostAddCountryId]             BIGINT          NULL,
    [RentPerMonth]                 DECIMAL (18, 2) NULL,
    [AddressInHomeCountry]         NVARCHAR (500)  COLLATE Latin1_General_CI_AS NULL,
    [HomeCountryId]                BIGINT          NULL,
    [BankingDetailsId]             BIGINT          NULL,
    [CustomerType]                 INT             NOT NULL,
    [NameOfKin]                    NVARCHAR (100)  NULL,
    [AddressOfKin]                 NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [ContactOfKin]                 NVARCHAR (50)   NULL,
    [CountryId]                    BIGINT          NULL,
    [IsActive]                     BIT             NOT NULL,
    [CreatedDate]                  DATETIME        NOT NULL,
    [ModifiedDate]                 DATETIME        NULL,
    [CreatedBy]                    INT             NOT NULL,
    [ModifiedBy]                   INT             NULL,
    [IsGuarantorApplication]       BIT             NULL,
    [RegularDriver]                BIT             NULL,
    [ConditionsResidentPermit]     NVARCHAR (100)  NULL,
    [LanguageId]                   BIGINT          NULL,
    [MarrageTypeId]                BIGINT          NULL,
    [SpousesName]                  NVARCHAR (100)  NULL,
    [SpousesBirthDate]             DATE            NULL,
    [PhyAddSurburb]                NVARCHAR (50)   NULL,
    [PhyAddTown]                   NVARCHAR (50)   NULL,
    [PostAddSurburb]               NVARCHAR (50)   NULL,
    [PostAddTown]                  NVARCHAR (50)   NULL,
    [SpecifyResidentialStatus]     NVARCHAR (100)  NULL,
    [PreviousHomeAddress]          NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PreferredCallTime]            BIGINT          NULL,
    [CompanyName]                  NVARCHAR (MAX)  NULL,
    [ComNatureOfBusiness]          BIGINT          NULL,
    [CompanyStartDate]             DATE            NULL,
    [ComTradeLicenceStartDate]     DATE            NULL,
    [ComTradeLicenceExpiryDate]    DATE            NULL,
    [ComVATNumber]                 NVARCHAR (50)   NULL,
    [ComPhyAddBuildingName]        NVARCHAR (200)  NULL,
    [ComPhyAddStreetName]          NVARCHAR (100)  NULL,
    [ComPhyAddEmirate]             BIGINT          NULL,
    [ComPhyAddPostCode]            NVARCHAR (100)  NULL,
    [ComPhyAddCountryId]           BIGINT          NULL,
    [ComTradingAs]                 NVARCHAR (50)   NULL,
    [ComRegistrationNumber]        NVARCHAR (50)   NULL,
    [ComNoOfYearsInBusiness]       INT             NULL,
    [ComLandlord]                  NVARCHAR (100)  NULL,
    [ComHoldingCompany]            NVARCHAR (100)  NULL,
    [ComAssociatedCompany]         NVARCHAR (200)  NULL,
    [ComSubsidaryCompany]          NVARCHAR (200)  NULL,
    [ComCompanyRepresentative]     NVARCHAR (100)  NULL,
    [ComFloorNo]                   INT             NULL,
    [ComYearsAtCurrentAddress]     INT             NULL,
    [ComEmirate]                   BIGINT          NULL,
    [PhyAdd1]                      NVARCHAR (200)  NULL,
    [PhyAdd2]                      NVARCHAR (200)  NULL,
    [PhyAdd3]                      NVARCHAR (200)  NULL,
    [PostAdd1]                     NVARCHAR (200)  NULL,
    [PostAdd2]                     NVARCHAR (200)  NULL,
    [PostAdd3]                     NVARCHAR (200)  NULL,
    [FinanceStatus]                BIGINT          NULL,
    [FinanceStatusNotes]           NVARCHAR (500)  NULL,
    [ConditionsOfResidentsPermit]  NVARCHAR (500)  NULL,
    [BusinessTypeId]               BIGINT          NULL,
    [QualificationId]              BIGINT          NULL,
    [PermitNumber]                 NVARCHAR (100)  NULL,
    [PermitIssueDate]              DATE            NULL,
    [PermitExpiryDate]             DATE            NULL,
    [IdIssueDate]                  DATE            NULL,
    [IdExpiryDate]                 DATE            NULL,
    [SpecifyMaritalStatus]         NVARCHAR (100)  NULL,
    [EthnicGroup]                  BIGINT          NULL,
    [MarketingSource]              BIGINT          NULL,
    [ClaimFreeGroup]               BIGINT          NULL,
    [IsCompanyVATRegistered]       BIT             NULL,
    [PhyAdd4]                      NVARCHAR (200)  NULL,
    [PhyAddCode]                   NVARCHAR (100)  NULL,
    [PostAdd4]                     NVARCHAR (200)  NULL,
    [PostAddCode]                  NVARCHAR (100)  NULL,
    [IsCompanyBlackOwned]          BIT             NULL,
    [IsCompanyBalanceSheet]        BIT             NULL,
    [CompanyFinancialYear]         NVARCHAR (200)  NULL,
    [CompanyTurnover]              DECIMAL (18, 4) NULL,
    [CompanyTotalAssets]           DECIMAL (18, 4) NULL,
    [NoOfMonthsAtPesentAddress]    NVARCHAR (50)   NULL,
    [ComPhyAdd1]                   NVARCHAR (200)  NULL,
    [ComPhyAdd2]                   NVARCHAR (200)  NULL,
    [ComPhyAdd3]                   NVARCHAR (200)  NULL,
    [ComPhyAdd4]                   NVARCHAR (200)  NULL,
    [ComPhyAddCode]                NVARCHAR (100)  NULL,
    [HomeCountryAddress1]          NVARCHAR (200)  NULL,
    [HomeCountryAddress2]          NVARCHAR (200)  NULL,
    [HomeCountryAddress3]          NVARCHAR (200)  NULL,
    [HomeCountryAddress4]          NVARCHAR (200)  NULL,
    [HomeCountryAddressCode]       NVARCHAR (100)  NULL,
    [PreferredLanguage]            NVARCHAR (200)  NULL,
    [TradeLicenseNumber]           NVARCHAR (200)  NULL,
    [IsSpouseDetailsIncluded]      BIT             CONSTRAINT [DF_TransactionClientHistory_IsSpouseDetailsIncluded] DEFAULT ((0)) NULL,
    [ComPhyAddMakaniNumber]        NVARCHAR (200)  NULL,
    [OfficeBuildingName]           NVARCHAR (200)  NULL,
    [OfficeStreetName]             NVARCHAR (200)  NULL,
    [OfficeEmirate]                BIGINT          NULL,
    [OfficeCountry]                BIGINT          NULL,
    [OfficeNearestLandmark]        NVARCHAR (200)  NULL,
    [OfficeMakaniNumber]           NVARCHAR (200)  NULL,
    [ComNumberofFleetVehicles]     BIGINT          NULL,
    [ComNumberofMortgagedVehicles] BIGINT          NULL,
    CONSTRAINT [PK_TransactionClientHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

