CREATE TABLE [dbo].[TransactionFinanceApplication] (
    [Id]                           BIGINT          IDENTITY (1, 1) NOT NULL,
    [TransactionId]                BIGINT          NOT NULL,
    [ClientId]                     BIGINT          NULL,
    [CompanyId]                    BIGINT          NULL,
    [CreatedDate]                  DATETIME        CONSTRAINT [DF_TransactionFinanceApplication_CreatedDate_1] DEFAULT (getutcdate()) NULL,
    [ModifiedDate]                 DATETIME        NULL,
    [CreatedBy]                    INT             NULL,
    [ModifiedBy]                   INT             NULL,
    [Response]                     NVARCHAR (4000) NULL,
    [CountryId]                    BIGINT          NULL,
    [IsActive]                     BIT             CONSTRAINT [DF__Transacti__IsAct__078F4C62] DEFAULT ((1)) NULL,
    [CompanyCompanyTypeId]         BIGINT          NULL,
    [FinanceStatusId]              BIGINT          NULL,
    [FinanceStatusNotes]           NVARCHAR (4000) NULL,
    [LeadNumber]                   BIGINT          NULL,
    [FinanceAccountNumber]         NVARCHAR (100)  NULL,
    [LOIIssueDate]                 DATETIME        NULL,
    [LOIExpiryDate]                DATETIME        NULL,
    [LocalPurchaseNumber]          NVARCHAR (200)  NULL,
    [LOPIssueDate]                 DATETIME        NULL,
    [LOPExpiryDate]                DATETIME        NULL,
    [BankersName]                  NVARCHAR (500)  NULL,
    [BankersOfficeTelephoneCode]   NVARCHAR (10)   NULL,
    [BankersOfficeTelephoneNumber] NVARCHAR (100)  NULL,
    [BankersMobileNumber]          NVARCHAR (100)  NULL,
    [BankersEmailAddress]          NVARCHAR (100)  NULL,
    [BankDealReferenceNumber]      NVARCHAR (100)  NULL,
    [IsUpdateStatustoTransaction]  BIT             NULL,
    [IsBankerUpdate]               BIT             NULL,
    [BankerNotes]                  NVARCHAR (4000) NULL,
    CONSTRAINT [TransactionFinanceApplication_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TransactionFinanceApplication_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_TransactionFinanceApplication_Transaction] FOREIGN KEY ([TransactionId]) REFERENCES [dbo].[Transaction] ([Id]),
    CONSTRAINT [FK_TransactionFinanceApplication_TransactionClient] FOREIGN KEY ([ClientId]) REFERENCES [dbo].[TransactionClient] ([Id]),
    CONSTRAINT [TransactionFinanceApplication_FK_Company] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[Company] ([Id]),
    CONSTRAINT [TransactionFinanceApplication_FK_CompanyCompanyTypeMapping] FOREIGN KEY ([CompanyCompanyTypeId]) REFERENCES [dbo].[CompanyCompanyTypeMapping] ([Id]),
    CONSTRAINT [TransactionFinanceApplication_FK_StaticValueFinanceStatus] FOREIGN KEY ([FinanceStatusId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionFinanceApplication_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionFinanceApplication_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

