CREATE TABLE [dbo].[TransactionContactHistory] (
    [Id]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [ApplicationHistoryId]        BIGINT          NOT NULL,
    [ContactId]                   BIGINT          NOT NULL,
    [TransactionId]               BIGINT          NOT NULL,
    [Title]                       BIGINT          NULL,
    [LastName]                    NVARCHAR (100)  COLLATE Latin1_General_CI_AS NOT NULL,
    [FirstName]                   NVARCHAR (100)  COLLATE Latin1_General_CI_AS NOT NULL,
    [MobileNumber]                NVARCHAR (50)   NULL,
    [AlternativeMobileNumber]     NVARCHAR (50)   NULL,
    [WorkTelephoneNumber]         NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [CountryId]                   BIGINT          NULL,
    [IsActive]                    BIT             NULL,
    [CreatedDate]                 DATETIME        NOT NULL,
    [ModifiedDate]                DATETIME        NULL,
    [CreatedBy]                   INT             NOT NULL,
    [ModifiedBy]                  INT             NULL,
    [RelationshipId]              BIGINT          NOT NULL,
    [SpouseEmployerName]          NVARCHAR (100)  NULL,
    [SpouseEmployerAddress]       NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [SpouseOccupationId]          BIGINT          NULL,
    [PeriodOfEmployment]          NVARCHAR (50)   NULL,
    [IsRegularDriver]             BIT             DEFAULT ((0)) NULL,
    [GenderId]                    BIGINT          NULL,
    [Initials]                    NVARCHAR (20)   NULL,
    [HomePhoneCode]               NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [HomePhoneNumber]             NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneCode]               NVARCHAR (20)   COLLATE Latin1_General_CI_AS NULL,
    [WorkPhoneNumber]             NVARCHAR (50)   COLLATE Latin1_General_CI_AS NULL,
    [IsSecondInsured]             BIT             DEFAULT ((0)) NOT NULL,
    [MiddleName]                  NVARCHAR (100)  NULL,
    [DriversLicenceNo]            NVARCHAR (100)  NULL,
    [DriversLicenceIssueDate]     DATE            NULL,
    [DriversLicenceExpiryDate]    DATE            NULL,
    [DriversLicenceIssuePlace]    NVARCHAR (200)  NULL,
    [Nationality]                 BIGINT          NULL,
    [DateofBirth]                 DATE            NULL,
    [PassportNo]                  NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PassportIssueDate]           DATE            NULL,
    [PassportExpiryDate]          DATE            NULL,
    [VisaNo]                      NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [VisaIssueDate]               DATE            NULL,
    [VisaExpiryDate]              DATE            NULL,
    [EmiratesIdNo]                NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [EmiratesIdIssueDate]         DATE            NULL,
    [EmiratesIdExpiryDate]        DATE            NULL,
    [EmiratesIdIssuePlace]        NVARCHAR (200)  NULL,
    [PhyAddBuildingName]          NVARCHAR (200)  NULL,
    [PhyAddArea]                  NVARCHAR (100)  NULL,
    [PhyAddEmirate]               BIGINT          NULL,
    [PhyAddCountryId]             BIGINT          NULL,
    [PostAddPOBoxNo]              NVARCHAR (200)  NULL,
    [PostAddEmirate]              BIGINT          NULL,
    [PostAddCountryId]            BIGINT          NULL,
    [ResidentialStatus]           BIGINT          NULL,
    [QualificationLevelId]        BIGINT          NULL,
    [EmailAddress]                NVARCHAR (100)  COLLATE Latin1_General_CI_AS NULL,
    [PhyAdd1]                     NVARCHAR (200)  NULL,
    [PhyAdd2]                     NVARCHAR (200)  NULL,
    [PhyAdd3]                     NVARCHAR (200)  NULL,
    [PostAdd1]                    NVARCHAR (200)  NULL,
    [PostAdd2]                    NVARCHAR (200)  NULL,
    [PostAdd3]                    NVARCHAR (200)  NULL,
    [IDNumber]                    NVARCHAR (200)  COLLATE Latin1_General_CI_AS NULL,
    [IdIssueDate]                 DATE            NULL,
    [IdExpiryDate]                DATE            NULL,
    [PermitNumber]                NVARCHAR (100)  NULL,
    [PermitIssueDate]             DATE            NULL,
    [PermitExpiryDate]            DATE            NULL,
    [UAEResidentSince]            DATE            NULL,
    [Occupation]                  NVARCHAR (200)  NULL,
    [Designation]                 NVARCHAR (200)  NULL,
    [PhyAdd4]                     NVARCHAR (200)  NULL,
    [PhyAddCode]                  NVARCHAR (100)  NULL,
    [PostAdd4]                    NVARCHAR (200)  NULL,
    [PostAddCode]                 NVARCHAR (100)  NULL,
    [LanguageId]                  BIGINT          NULL,
    [ConditionsOfResidentsPermit] NVARCHAR (500)  NULL,
    [MaritalStatusId]             BIGINT          NULL,
    [MarriageDate]                DATE            NULL,
    [NoofDependents]              INT             NULL,
    [MarrageTypeId]               BIGINT          NULL,
    [SpecifyMaritalStatus]        NVARCHAR (100)  NULL,
    [NoOfYearsAtPesentAddress]    INT             NULL,
    [NoOfMonthsAtPesentAddress]   INT             NULL,
    [PreferedMailingAddress]      BIGINT          NULL,
    [PreferedContactMethod]       BIGINT          NULL,
    [CountryOfBirth]              BIGINT          NULL,
    [PreviousAdd1]                NVARCHAR (200)  NULL,
    [PreviousAdd2]                NVARCHAR (200)  NULL,
    [PreviousAdd3]                NVARCHAR (200)  NULL,
    [PreviousAdd4]                NVARCHAR (50)   NULL,
    [PreviousAddCode]             NVARCHAR (100)  NULL,
    [NoOfYearsAtPreviousAddress]  INT             NULL,
    [NoOfMonthsAtPreviousAddress] INT             NULL,
    [IsDualCitizenship]           BIT             NULL,
    [DualCitizenshipCountryId]    BIGINT          NULL,
    [HomeCountryId]               BIGINT          NULL,
    [AddressInHomeCountry]        NVARCHAR (500)  NULL,
    [ContactNumberInHomeCountry]  NVARCHAR (50)   NULL,
    [ShareholdingPercentage]      DECIMAL (18, 2) NULL,
    [IsOwnHome]                   BIT             NULL,
    [HomeCountryAddress1]         NVARCHAR (200)  NULL,
    [HomeCountryAddress2]         NVARCHAR (200)  NULL,
    [HomeCountryAddress3]         NVARCHAR (200)  NULL,
    [HomeCountryAddress4]         NVARCHAR (200)  NULL,
    [HomeCountryAddressCode]      NVARCHAR (100)  NULL,
    [IsContract]                  BIT             NULL,
    [IsSurety]                    BIT             NULL,
    [IsThirdPartyRegistration]    BIT             NULL,
    [JoiningDate]                 DATE            NULL,
    [MakaniNumber]                NVARCHAR (200)  NULL,
    [TradeLicenseNumber]          NVARCHAR (200)  NULL,
    [TradelicenseExpiryDate]      DATE            NULL,
    [DateofInception]             DATE            NULL,
    [EmploymentCategoryId]        BIGINT          NULL,
    [PhyAddNearestLandMark]       NVARCHAR (200)  NULL,
    [FaxCode]                     NVARCHAR (10)   NULL,
    [FaxNumber]                   NVARCHAR (50)   NULL,
    CONSTRAINT [PK_TransactionContactHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

