CREATE TABLE [dbo].[TransactionIncomeAndExpenditure] (
    [Id]                                      BIGINT          IDENTITY (1, 1) NOT NULL,
    [TransactionId]                           BIGINT          NULL,
    [MonthlySalary]                           DECIMAL (18, 2) NULL,
    [Allowance]                               DECIMAL (18, 2) NULL,
    [OtherIncome]                             DECIMAL (18, 2) NULL,
    [CreatedDate]                             DATETIME        NULL,
    [ModifiedDate]                            DATETIME        NULL,
    [CreatedBy]                               INT             NULL,
    [ModifiedBy]                              INT             NULL,
    [CountryId]                               BIGINT          NULL,
    [IsActive]                                BIT             NULL,
    [TotalIncome]                             DECIMAL (18, 2) NULL,
    [IsOwnHome]                               BIT             NULL,
    [BondHolderBank]                          NVARCHAR (500)  NULL,
    [Surburb]                                 NVARCHAR (100)  NULL,
    [OutstandingBondAmount]                   DECIMAL (18, 2) NULL,
    [RentalValue]                             DECIMAL (18, 2) NULL,
    [LandlordName]                            NVARCHAR (200)  NULL,
    [LandlordAddress]                         NVARCHAR (500)  NULL,
    [HowAreYouPaid]                           BIGINT          NULL,
    [NonMonetaryBenefits]                     DECIMAL (18, 2) NULL,
    [Expenditure]                             DECIMAL (18, 2) NULL,
    [Deductions]                              DECIMAL (18, 2) NULL,
    [Taxation]                                DECIMAL (18, 2) NULL,
    [Pension]                                 DECIMAL (18, 2) NULL,
    [MedicalAidHospitalPlan]                  DECIMAL (18, 2) NULL,
    [LifeAssurancePremuims]                   DECIMAL (18, 2) NULL,
    [RetirementAnnuityPremuims]               DECIMAL (18, 2) NULL,
    [BondRepayments]                          DECIMAL (18, 2) NULL,
    [WaterElectricty]                         DECIMAL (18, 2) NULL,
    [RatesTaxes]                              DECIMAL (18, 2) NULL,
    [LoanRepayments]                          DECIMAL (18, 2) NULL,
    [CreditCardRepayments]                    DECIMAL (18, 2) NULL,
    [InsurancePremiums]                       DECIMAL (18, 2) NULL,
    [Household]                               DECIMAL (18, 2) NULL,
    [MotorVehicles]                           DECIMAL (18, 2) NULL,
    [FurnitureAccounts]                       DECIMAL (18, 2) NULL,
    [Groceries]                               DECIMAL (18, 2) NULL,
    [SchoolFees]                              DECIMAL (18, 2) NULL,
    [ClothingAccounts]                        DECIMAL (18, 2) NULL,
    [Transport]                               DECIMAL (18, 2) NULL,
    [BudgetedSavings]                         DECIMAL (18, 2) NULL,
    [Maintenance]                             DECIMAL (18, 2) NULL,
    [DomesticStaff]                           DECIMAL (18, 2) NULL,
    [Cellphone]                               DECIMAL (18, 2) NULL,
    [Entertainment]                           DECIMAL (18, 2) NULL,
    [MNET]                                    DECIMAL (18, 2) NULL,
    [ArmedResponse]                           DECIMAL (18, 2) NULL,
    [Gym]                                     DECIMAL (18, 2) NULL,
    [TotalExpenditure]                        DECIMAL (18, 2) NULL,
    [MonthlyBondInstallment]                  DECIMAL (18, 2) NULL,
    [PurchasePrice]                           DECIMAL (18, 2) NULL,
    [PurchaseDate]                            DATE            NULL,
    [PresentMarketValue]                      DECIMAL (18, 2) NULL,
    [RegisterdTo]                             NVARCHAR (200)  NULL,
    [StandNumber]                             INT             NULL,
    [IsGuarantor]                             INT             NOT NULL,
    [GrossMonthlySalary]                      DECIMAL (18, 2) NULL,
    [IsDeclaredInsolvent]                     BIT             NULL,
    [RehabilitationDate]                      DATE            NULL,
    [IsUnderDebtReview]                       BIT             NULL,
    [IsGuarantorsDetails]                     BIT             NULL,
    [GuarantorDetails]                        NVARCHAR (200)  NULL,
    [IsShareholderInCompany]                  BIT             NULL,
    [ShareholdersDetail]                      NVARCHAR (200)  NULL,
    [IsShareDetailsWithinCompany]             BIT             NULL,
    [IsShareDetailsAmongPartner]              BIT             NULL,
    [IsReceiveMarketingInfo]                  BIT             NULL,
    [IsShareDetailsToFinancialInstitute]      BIT             NULL,
    [IsDisclosureofPersonalInfo]              BIT             NULL,
    [IsDebitOrderInformationAndAuthorization] BIT             NULL,
    [BasicMonthlySalary]                      DECIMAL (18, 4) NULL,
    [HomeLoanSubsidy]                         DECIMAL (18, 4) NULL,
    [CarAllowance]                            DECIMAL (18, 4) NULL,
    [OvertimeAndCommission]                   DECIMAL (18, 4) NULL,
    [SalaryDeductions]                        DECIMAL (18, 4) NULL,
    [SocialSecurity]                          DECIMAL (18, 4) NULL,
    [RentalIncome]                            DECIMAL (18, 4) NULL,
    [OtherDescription]                        NVARCHAR (500)  NULL,
    [OverdraftRepayments]                     DECIMAL (18, 4) NULL,
    [IsCreditRehabilitation]                  BIT             NULL,
    [ObtainCustomerBankStatements]            BIT             NULL,
    [ObtainCustomerSalaryAdvice]              BIT             NULL,
    [IsObtainCreditLifeInsurance]             BIT             NULL,
    [OtherIncomeSource]                       DECIMAL (18, 4) NULL,
    [OtherAllowance]                          DECIMAL (18, 4) NULL,
    [LoanRepayments1]                         DECIMAL (18, 4) NULL,
    [LoanRepayments2]                         DECIMAL (18, 4) NULL,
    [LoanRepayments3]                         DECIMAL (18, 4) NULL,
    [LoanRepayments4]                         DECIMAL (18, 4) NULL,
    [LoanProviderId]                          BIGINT          NULL,
    [Loan1ProviderId]                         BIGINT          NULL,
    [Loan2ProviderId]                         BIGINT          NULL,
    [Loan3ProviderId]                         BIGINT          NULL,
    [Loan4ProviderId]                         BIGINT          NULL,
    [LoanIsSettled]                           BIT             NULL,
    [Loan1IsSettled]                          BIT             NULL,
    [Loan2IsSettled]                          BIT             NULL,
    [Loan3IsSettled]                          BIT             NULL,
    [Loan4IsSettled]                          BIT             NULL,
    [OtherExpenses]                           DECIMAL (18, 4) NULL,
    [SalaryCertificateExpiryDate]             DATE            NULL,
    [SalaryReceivedDate1]                     DATE            NULL,
    [SalaryReceivedDate2]                     DATE            NULL,
    [SalaryReceivedDate3]                     DATE            NULL,
    [OwnerShipTypeId]                         BIGINT          NULL,
    [InWhoseName]                             NVARCHAR (100)  NULL,
    [FrequencyId]                             BIGINT          NULL,
    CONSTRAINT [PK_TransactionIncomeAndExpenditure] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TransactionIncomeAndExpenditure_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_TransactionIncomeAndExpenditure_StaticValueHowAreYouPaid] FOREIGN KEY ([HowAreYouPaid]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionIncomeAndExpenditure_Transaction] FOREIGN KEY ([TransactionId]) REFERENCES [dbo].[Transaction] ([Id]),
    CONSTRAINT [FK_TransactionIncomeAndExpenditure_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_TransactionIncomeAndExpenditure_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionIncomeAndExpenditure_FK_StaticValueFrequencyId] FOREIGN KEY ([FrequencyId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionIncomeAndExpenditure_FK_StaticValueOwnerShipTypeId] FOREIGN KEY ([OwnerShipTypeId]) REFERENCES [dbo].[StaticValue] ([Id])
);

