CREATE TABLE [dbo].[TransactionHistory] (
    [Id]                               BIGINT          IDENTITY (1, 1) NOT NULL,
    [ApplicationHistoryId]             BIGINT          NOT NULL,
    [TransactionId]                    BIGINT          NOT NULL,
    [GroupId]                          BIGINT          NOT NULL,
    [BranchId]                         BIGINT          NOT NULL,
    [TransactionTypeId]                BIGINT          NULL,
    [TransactionStatusId]              BIGINT          NULL,
    [TransactionStatusNotes]           NVARCHAR (4000) NULL,
    [FinanceStatusId]                  BIGINT          NULL,
    [FinanceStatusNotes]               NVARCHAR (4000) NULL,
    [IsDealSighted]                    BIT             NOT NULL,
    [SalesCompanyId]                   BIGINT          NULL,
    [SalesReferenceNumber]             NVARCHAR (100)  NULL,
    [SalesPersonId]                    BIGINT          NULL,
    [BusinessManagerId]                INT             NULL,
    [CompanyType]                      BIGINT          NULL,
    [IsCashTransaction]                BIT             NOT NULL,
    [PreferredInterestRate]            DECIMAL (18, 2) NULL,
    [FinanceCompanyId]                 BIGINT          NULL,
    [IsPreArrangedFinance]             BIT             NOT NULL,
    [FinanceAccountNumber]             NVARCHAR (100)  NULL,
    [FinanceTermId]                    BIGINT          NULL,
    [VehicleId]                        BIGINT          NULL,
    [VehicleUse]                       BIGINT          NULL,
    [VehicleCondition]                 BIGINT          NULL,
    [VehicleRegistrationName]          NVARCHAR (100)  NULL,
    [VehicleRegisteredAt]              NVARCHAR (100)  NULL,
    [ValuationDate]                    DATE            NULL,
    [Valuator]                         NVARCHAR (100)  NULL,
    [DisburseId]                       BIGINT          NULL,
    [PrivateKey]                       NVARCHAR (100)  NULL,
    [IsAssetInsured]                   BIT             NULL,
    [RetailPrice]                      DECIMAL (18, 2) NULL,
    [Discount]                         DECIMAL (18, 2) NULL,
    [TotalDeposit]                     DECIMAL (18, 2) NULL,
    [BalloonValue]                     DECIMAL (18, 2) NULL,
    [BalloonPercentage]                DECIMAL (18, 2) NULL,
    [IsTradeIn]                        BIT             NULL,
    [IsTradeInCashTransaction]         BIT             NULL,
    [TradeInFinanceCompanyId]          BIGINT          NULL,
    [TradeInCarFinanceAccNumber]       NVARCHAR (100)  NULL,
    [TradeInCurrentInstalment]         DECIMAL (18, 2) NULL,
    [TradeInValue]                     DECIMAL (18, 2) NULL,
    [TradeInSettlementValue]           DECIMAL (18, 2) NULL,
    [TradeInCashPayback]               DECIMAL (18, 2) NULL,
    [NetTradeInDepositValue]           DECIMAL (18, 2) NULL,
    [TransactionClientId]              BIGINT          NULL,
    [TransactionDriverId]              BIGINT          NULL,
    [ChassisNumber]                    NVARCHAR (100)  NULL,
    [EngineNumber]                     NVARCHAR (100)  NULL,
    [RegistrationNumber]               NVARCHAR (100)  NULL,
    [FirstRegistrationDate]            DATETIME        NULL,
    [Color]                            NVARCHAR (50)   NULL,
    [VehicleEmirate]                   BIGINT          NULL,
    [DownPayment]                      DECIMAL (18, 2) NULL,
    [CountryId]                        BIGINT          NULL,
    [IsActive]                         BIT             NOT NULL,
    [CreatedDate]                      DATETIME        NOT NULL,
    [ModifiedDate]                     DATETIME        NULL,
    [CreatedBy]                        INT             NOT NULL,
    [ModifiedBy]                       INT             NULL,
    [InterestRateTypeId]               BIGINT          NULL,
    [PaymentType]                      BIGINT          NULL,
    [ReferenceNumber]                  NVARCHAR (50)   NULL,
    [OdometerReading]                  INT             NULL,
    [FinanceType]                      BIGINT          NULL,
    [SellingPrice]                     DECIMAL (18, 2) NULL,
    [VehicleCostPrice]                 DECIMAL (18, 2) NULL,
    [Immoblizer]                       BIGINT          NULL,
    [IsManufacturerWarranty]           BIT             NULL,
    [ManWarrantyExpiryMonths]          BIGINT          NULL,
    [ManWarrantyExpiryKM]              INT             NULL,
    [ExistingWarranty]                 BIT             NULL,
    [ExistingWarrantyExpiryDate]       DATE            NULL,
    [ExistingWarrantyExpiryKM]         INT             NULL,
    [ManufacturePlanType]              BIGINT          NULL,
    [ManPlanExpiryMonths]              BIGINT          NULL,
    [ManPlanExpiryKM]                  INT             NULL,
    [ExistingPlanType]                 BIGINT          NULL,
    [ExistingPlanExpiryDate]           DATE            NULL,
    [ExistingPlanExpiryKM]             INT             NULL,
    [IsIncepted]                       BIT             DEFAULT ((0)) NOT NULL,
    [VehicleDescription]               NVARCHAR (200)  NULL,
    [ProfitRate]                       DECIMAL (18, 2) NULL,
    [PreferredCallTime]                BIGINT          NULL,
    [VehicleTradeInValue]              DECIMAL (18, 2) NULL,
    [IsManufaturerApprovedUsedVehicle] BIT             NULL,
    [IsFullServiceHistory]             BIT             NULL,
    [Kilometers]                       INT             NULL,
    [VINNumber]                        NVARCHAR (50)   NULL,
    [TransactionNo]                    BIGINT          NULL,
    [InceptDate]                       DATETIME        NULL,
    [BankDocumentationFees]            DECIMAL (18, 2) NULL,
    [StampDutyFees]                    DECIMAL (18, 2) NULL,
    [CallBackCustomerDateTime]         DATETIME        NULL,
    [DeclineDateTime]                  DATETIME        NULL,
    [TransactionAPIOwner]              INT             NULL,
    [HFAId]                            BIGINT          NULL,
    [DocInvoiceNo]                     NVARCHAR (50)   NULL,
    [StockNo]                          NVARCHAR (50)   NULL,
    [DocInvoiceDate]                   DATETIME        NULL,
    [DocInvoicePaidDate]               DATETIME        NULL,
    [VehicleDeliveryDate]              DATETIME        NULL,
    [OtherFee]                         DECIMAL (18, 2) NULL,
    [OtherCost]                        DECIMAL (18, 2) NULL,
    [DICAmount]                        DECIMAL (18, 2) NULL,
    [DICPercentage]                    DECIMAL (18, 2) NULL,
    [PayOutRequestDate]                DATETIME        NULL,
    [TransactionSource]                NVARCHAR (100)  NULL,
    [SeatingCapacity]                  INT             NULL,
    [PrimeInterestRate]                DECIMAL (18, 2) NULL,
    [IsBlockAutomaticUpdate]           BIT             CONSTRAINT [DF_TransactionHistory_IsBlockAutomaticUpdate] DEFAULT ((0)) NULL,
    [APICompanyId]                     BIGINT          NULL,
    [IsApiUpdate]                      BIT             CONSTRAINT [DF_TransactionHistory_IsApiUpdate] DEFAULT ((0)) NULL,
    [FleetNumber]                      NVARCHAR (MAX)  NULL,
    [BusinessSegment]                  BIGINT          NULL,
    [ParentTransactionId]              BIGINT          NULL,
    [TransactionFee]                   DECIMAL (18, 2) NULL,
    [LOIIssueDate]                     DATETIME        NULL,
    [LOIExpiryDate]                    DATETIME        NULL,
    [LocalPurchaseNumber]              NVARCHAR (200)  NULL,
    [LOPIssueDate]                     DATETIME        NULL,
    [LOPExpiryDate]                    DATETIME        NULL,
    [CopiedFrom]                       NVARCHAR (MAX)  NULL,
    [Scheme]                           NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_TransactionHistory] PRIMARY KEY CLUSTERED ([Id] ASC)
);

