CREATE TABLE [dbo].[TransactionItem] (
    [Id]                    BIGINT          IDENTITY (1, 1) NOT NULL,
    [TransactionId]         BIGINT          NULL,
    [ItemTypeId]            BIGINT          NULL,
    [ItemUseId]             BIGINT          NULL,
    [ItemDescription]       NVARCHAR (2000) NULL,
    [ItemCode]              NVARCHAR (100)  NULL,
    [ItemSerialNumber]      NVARCHAR (100)  NULL,
    [ItemCost]              DECIMAL (18, 8) NULL,
    [ItemRetailValue]       DECIMAL (18, 8) NULL,
    [ItemQuantity]          INT             NULL,
    [TotalItemsRetailValue] DECIMAL (18, 8) NULL,
    [LoanAmountAppliedFor]  DECIMAL (18, 8) NULL,
    [Discount]              DECIMAL (18, 8) NULL,
    [Notes]                 NVARCHAR (2000) NULL,
    [IsActive]              BIT             DEFAULT ((1)) NOT NULL,
    [CountryId]             BIGINT          NULL,
    [CreatedBy]             INT             NULL,
    [ModifiedBy]            INT             NULL,
    [CreatedDate]           DATETIME        DEFAULT (getutcdate()) NULL,
    [ModifiedDate]          DATETIME        NULL,
    [MaxLoanApproved]       DECIMAL (18, 8) NULL,
    [ItemInvoiceNo]         NVARCHAR (50)   NULL,
    [ItemStockNo]           NVARCHAR (50)   NULL,
    [ItemInvoiceDate]       DATETIME        NULL,
    [ItemInvoicePaidDate]   DATETIME        NULL,
    [ItemDeliveryDate]      DATETIME        NULL,
    [IncludeInLead]         BIT             NULL,
    [Deposit]               DECIMAL (18, 8) NULL,
    CONSTRAINT [TransactionItem_PK] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [TransactionItem_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionItem_FK_ItemTypes] FOREIGN KEY ([ItemTypeId]) REFERENCES [dbo].[ItemTypes] ([Id]),
    CONSTRAINT [TransactionItem_FK_ItemUse] FOREIGN KEY ([ItemUseId]) REFERENCES [dbo].[ItemUse] ([Id]),
    CONSTRAINT [TransactionItem_FK_Transaction] FOREIGN KEY ([TransactionId]) REFERENCES [dbo].[Transaction] ([Id]),
    CONSTRAINT [TransactionItem_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionItem_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id])
);

