CREATE TABLE [dbo].[TransactionVehicle] (
    [Id]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [TransactionId]              BIGINT          NULL,
    [VehicleId]                  BIGINT          NULL,
    [FinanceInitiationFee]       DECIMAL (18, 4) NULL,
    [TotalDeposit]               DECIMAL (18, 4) NULL,
    [IsVehicleTrackingInstalled] BIT             NULL,
    [IsActive]                   BIT             NULL,
    [CountryId]                  BIGINT          NULL,
    [CreatedDate]                DATETIME        NULL,
    [ModifiedDate]               DATETIME        NULL,
    [CreatedBy]                  INT             NULL,
    [ModifiedBy]                 INT             NULL,
    [IsVehicleUsedBySecurity]    BIT             NULL,
    [OffRoadUsages]              DECIMAL (18, 2) NULL,
    [Valuator]                   NVARCHAR (200)  NULL,
    [ValuationDate]              DATETIME        NULL,
    [DownPaymentMadeTo]          BIGINT          NULL,
    [RateMargin]                 DECIMAL (18, 2) NULL,
    [BookAssetValue]             DECIMAL (18, 2) NULL,
    [AgencyBranchId]             BIGINT          NULL,
    [AgencyLocation]             NVARCHAR (200)  NULL,
    [TrafficFileNo]              NVARCHAR (100)  NULL,
    [RegistrationTypeId]         BIGINT          NULL,
    [RegistrationName]           NVARCHAR (200)  NULL,
    [ThirdPartyRelationId]       BIGINT          NULL,
    [ModeOfDownPayment]          BIGINT          NULL,
    [SUKUKAmount]                DECIMAL (18, 2) NULL,
    [SUKUKTenure]                INT             NULL,
    [FeesCollection]             BIGINT          NULL,
    CONSTRAINT [PK_TransactionVehicle] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [TransactionVehicle_FK_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_DownPaymentMadeTo] FOREIGN KEY ([DownPaymentMadeTo]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_StaticValueAgencyBranchId] FOREIGN KEY ([AgencyBranchId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_StaticValueFeesCollection] FOREIGN KEY ([FeesCollection]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_StaticValueModeOfDownPayment] FOREIGN KEY ([ModeOfDownPayment]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_StaticValueRegistrationTypeId] FOREIGN KEY ([RegistrationTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_StaticValueThirdPartyRelationId] FOREIGN KEY ([ThirdPartyRelationId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_Transaction] FOREIGN KEY ([TransactionId]) REFERENCES [dbo].[Transaction] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_UsersCreatedBy] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_UsersModifiedBy] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionVehicle_FK_Vehicle] FOREIGN KEY ([VehicleId]) REFERENCES [dbo].[Vehicle] ([Id])
);

