CREATE TABLE [dbo].[TransactionEmployerDetails] (
    [Id]                                  BIGINT         IDENTITY (1, 1) NOT NULL,
    [TransactionId]                       BIGINT         NOT NULL,
    [EmploymentTypeId]                    BIGINT         NULL,
    [NameofEmployer]                      NVARCHAR (200) NULL,
    [JoiningDate]                         DATE           NULL,
    [EmployeeNumber]                      NVARCHAR (200) NULL,
    [Designation]                         NVARCHAR (200) NULL,
    [TypeOfOrganization]                  BIGINT         NULL,
    [Sector]                              NVARCHAR (200) NULL,
    [PreviousEmployer]                    NVARCHAR (200) NULL,
    [NoOfYearsWithPreviousEmployer]       INT            NULL,
    [BusinessName]                        NVARCHAR (200) NULL,
    [DateofInception]                     DATE           NULL,
    [TradeLicenceNo]                      NVARCHAR (200) NULL,
    [TradeLicenceExpiryDate]              DATE           NULL,
    [CreatedDate]                         DATETIME       CONSTRAINT [DF_TransactionFinanceApplication_CreatedDate] DEFAULT (getutcdate()) NOT NULL,
    [ModifiedDate]                        DATETIME       NULL,
    [CreatedBy]                           INT            NULL,
    [ModifiedBy]                          INT            NULL,
    [IsActive]                            BIT            DEFAULT ((1)) NULL,
    [CountryId]                           BIGINT         NULL,
    [Occupation]                          NVARCHAR (100) NULL,
    [SalaryCycle]                         BIGINT         NULL,
    [NoOfEmployees]                       INT            NULL,
    [WebsiteOfEmployer]                   NVARCHAR (200) NULL,
    [PhyAdd1]                             NVARCHAR (200) NULL,
    [PhyAdd2]                             NVARCHAR (200) NULL,
    [PhyAdd3]                             NVARCHAR (200) NULL,
    [PhyAdd4]                             NVARCHAR (200) NULL,
    [Code]                                NVARCHAR (50)  NULL,
    [NatureOfBusiness]                    BIGINT         NULL,
    [EmploymentCategoryId]                BIGINT         NULL,
    [SectorId]                            BIGINT         NULL,
    [MODRank]                             NVARCHAR (200) NULL,
    [PreviousEmployerAddress]             NVARCHAR (500) NULL,
    [PreviousEmployerTelephoneNumberCode] NVARCHAR (10)  NULL,
    [PreviousEmployerTelephoneNumber]     NVARCHAR (50)  NULL,
    [CurrentEmployerDateOfEstablishment]  DATE           NULL,
    [OccupationLevelId]                   BIGINT         NULL,
    [DesignationId]                       BIGINT         NULL,
    CONSTRAINT [PK_TransactionFinanceApplication] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_TransactionEmployerDetails_Country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[Country] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_EmployerCategoryId] FOREIGN KEY ([EmploymentCategoryId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_StaticValueDesignationId] FOREIGN KEY ([DesignationId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_StaticValueEmploymentTypeId] FOREIGN KEY ([EmploymentTypeId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_StaticValueTypeOfOrganization] FOREIGN KEY ([TypeOfOrganization]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_Transaction] FOREIGN KEY ([TransactionId]) REFERENCES [dbo].[Transaction] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_TransactionEmployerDetails_NatureOfBusiness] FOREIGN KEY ([NatureOfBusiness]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_Users] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_TransactionEmployerDetails_Users1] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [TransactionEmployerDetails_FK_StaticValue] FOREIGN KEY ([SectorId]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionEmployerDetails_FK_StaticValueSalaryCycle] FOREIGN KEY ([SalaryCycle]) REFERENCES [dbo].[StaticValue] ([Id]),
    CONSTRAINT [TransactionEmployerDetails_OccupationLevelId_FK_StaticValue] FOREIGN KEY ([OccupationLevelId]) REFERENCES [dbo].[StaticValue] ([Id])
);

